// Package webvocab renders the web UI's copy of the compiled-in vocabulary —
// statuses with their roles, types with their hierarchy rules, priorities,
// estimates, status groups and creation defaults — as a TypeScript module the
// web imports instead of hand-mirroring the Go definitions. `task codegen`
// (via go:generate) writes the file; the committed output is pinned by
// TestGeneratedVocabularyIsFresh, so the web never depends on running Go and a
// vocabulary change fails the suite until the file is regenerated.
//
// Colors and icons deliberately do not cross this boundary: they are
// presentation, owned by each surface's theme.
package webvocab

//go:generate go run ./gen

import (
	"fmt"
	"strings"

	"github.com/alphaleonis/nibs/internal/config"
	"github.com/alphaleonis/nibs/internal/estimate"
	"github.com/alphaleonis/nibs/internal/nibtypes"
)

// OutputPath is the module-root-relative path of the generated file.
const OutputPath = "web/src/lib/generated/vocabulary.ts"

// roleNames lists every config.Role the generator knows how to spell, in the
// order the TS union declares them. Render errors on a role outside this list
// rather than emitting a name the TS side never classified.
var roleNames = []config.Role{
	config.RoleOpen,
	config.RoleStartable,
	config.RoleParked,
	config.RoleDone,
	config.RoleDropped,
}

// Render returns the full generated TypeScript module.
func Render() (string, error) {
	cfg := config.Default()
	var b strings.Builder

	b.WriteString("// Code generated by internal/webvocab. DO NOT EDIT.\n")
	b.WriteString("// Regenerate with `task codegen`.\n")
	b.WriteString("//\n")
	b.WriteString("// The compiled-in vocabulary, rendered from the Go definitions\n")
	b.WriteString("// (internal/config, internal/nibtypes, internal/estimate). The committed\n")
	b.WriteString("// file is pinned byte-for-byte by TestGeneratedVocabularyIsFresh.\n\n")

	// The role union. A new Go role lands here on regeneration, and every
	// exhaustive switch over StatusRole in the web then fails svelte-check
	// until the new role is classified — the NibFilter-guard philosophy.
	names := make([]string, len(roleNames))
	for i, r := range roleNames {
		names[i] = fmt.Sprintf("%q", r.String())
	}
	b.WriteString("/** A status's lifecycle role — the Go config.Role enum. */\n")
	b.WriteString("export type StatusRole = " + strings.Join(names, " | ") + ";\n\n")

	b.WriteString("/** Statuses in rank order (Go config.DefaultStatuses) — the sort priority lists use. */\n")
	b.WriteString("export const STATUS_DEFS: readonly { readonly name: string; readonly role: StatusRole }[] = [\n")
	for _, s := range config.DefaultStatuses {
		if !knownRole(s.Role) {
			return "", fmt.Errorf("status %q carries role %v, which the generator does not know how to spell — classify it in roleNames and in every StatusRole switch", s.Name, s.Role)
		}
		fmt.Fprintf(&b, "  { name: %q, role: %q },\n", s.Name, s.Role.String())
	}
	b.WriteString("];\n\n")

	b.WriteString("/** Statuses in workflow (transition) order — the order choosers list. */\n")
	writeStringArray(&b, "STATUS_WORKFLOW_ORDER", cfg.WorkflowStatusNames())

	b.WriteString("/** Status-group names shared with the CLI: `-s open` is `status:open`. */\n")
	fmt.Fprintf(&b, "export const STATUS_GROUP_OPEN = %q;\n", config.StatusGroupOpen)
	fmt.Fprintf(&b, "export const STATUS_GROUP_CLOSED = %q;\n\n", config.StatusGroupClosed)

	writeStringArray(&b, "TYPES", typeNames())

	b.WriteString("/** Parent type → legal child types (Go nibtypes.ValidChildTypes). */\n")
	b.WriteString("export const VALID_CHILD_TYPES: Record<string, readonly string[]> = {\n")
	for _, t := range typeNames() {
		children := nibtypes.ValidChildTypes(t)
		quoted := make([]string, len(children))
		for i, c := range children {
			quoted[i] = fmt.Sprintf("%q", c)
		}
		fmt.Fprintf(&b, "  %s: [%s],\n", t, strings.Join(quoted, ", "))
	}
	b.WriteString("};\n\n")

	b.WriteString("/** Container→leaf rank derived from the hierarchy: a leaf ranks 0, a container one above its highest child. */\n")
	b.WriteString("export const TYPE_RANK: Record<string, number> = {\n")
	ranks := typeRanks()
	for _, t := range typeNames() {
		fmt.Fprintf(&b, "  %s: %d,\n", t, ranks[t])
	}
	b.WriteString("};\n\n")

	writeStringArray(&b, "PRIORITIES", priorityNames())

	b.WriteString("/** Estimates with their point weights and display labels. */\n")
	b.WriteString("export const ESTIMATE_DEFS: readonly { readonly name: string; readonly weight: number; readonly label: string }[] = [\n")
	for _, e := range config.DefaultEstimates {
		fmt.Fprintf(&b, "  { name: %q, weight: %d, label: %q },\n", e.Name, estimate.Weight(e.Name), estimateLabel(e.Name))
	}
	b.WriteString("];\n\n")

	b.WriteString("/** Creation defaults (Go config defaults for a new nib). */\n")
	fmt.Fprintf(&b, "export const DEFAULT_STATUS = %q;\n", cfg.Nibs.DefaultStatus)
	fmt.Fprintf(&b, "export const DEFAULT_TYPE = %q;\n", cfg.Nibs.DefaultType)

	return b.String(), nil
}

func knownRole(r config.Role) bool {
	for _, k := range roleNames {
		if r == k {
			return true
		}
	}
	return false
}

func writeStringArray(b *strings.Builder, name string, values []string) {
	quoted := make([]string, len(values))
	for i, v := range values {
		quoted[i] = fmt.Sprintf("%q", v)
	}
	fmt.Fprintf(b, "export const %s: readonly string[] = [%s];\n\n", name, strings.Join(quoted, ", "))
}

func typeNames() []string {
	names := make([]string, len(config.DefaultTypes))
	for i, t := range config.DefaultTypes {
		names[i] = t.Name
	}
	return names
}

func priorityNames() []string {
	names := make([]string, len(config.DefaultPriorities))
	for i, p := range config.DefaultPriorities {
		names[i] = p.Name
	}
	return names
}

// typeRanks derives the container→leaf rank of every type from the hierarchy
// rules: a type with no legal children ranks 0, a container one above its
// highest-ranked possible child. The hierarchy is acyclic by construction (a
// type never appears among its own descendants' children), so the recursion
// terminates.
func typeRanks() map[string]int {
	ranks := make(map[string]int, len(config.DefaultTypes))
	var rank func(t string) int
	rank = func(t string) int {
		if r, ok := ranks[t]; ok {
			return r
		}
		max := -1
		for _, c := range nibtypes.ValidChildTypes(t) {
			if r := rank(c); r > max {
				max = r
			}
		}
		ranks[t] = max + 1
		return ranks[t]
	}
	for _, t := range typeNames() {
		rank(t)
	}
	return ranks
}

// estimateLabel derives an estimate's display label from its declared
// description, which carries the label followed by a parenthesized weight
// ("Small (1 point)"). TestEstimateLabels pins the results.
func estimateLabel(name string) string {
	for _, e := range config.DefaultEstimates {
		if e.Name == name {
			label, _, _ := strings.Cut(e.Description, " (")
			return strings.TrimSpace(label)
		}
	}
	return name
}
