// Package webvocab renders the compiled-in vocabulary (statuses with their
// roles, types with their hierarchy rules, priorities, estimates, status groups
// and creation defaults) as a TypeScript module the web imports. `task codegen`
// writes it through go:generate; TestGeneratedVocabularyIsFresh fails until the
// committed file matches.
//
// Colors and icons stay out: each surface's theme owns them.
package webvocab

//go:generate go run ./gen

import (
	"fmt"
	"strings"

	"github.com/alphaleonis/nibs/internal/config"
	"github.com/alphaleonis/nibs/internal/estimate"
	"github.com/alphaleonis/nibs/internal/nibtypes"
)

// OutputPath is the module-root-relative path of the generated file.
const OutputPath = "web/src/lib/generated/vocabulary.ts"

// roleNames lists the config.Roles the generator can spell, in StatusRole union
// order. Render refuses a status whose role is missing here.
var roleNames = []config.Role{
	config.RoleOpen,
	config.RoleStartable,
	config.RoleParked,
	config.RoleDone,
	config.RoleDropped,
}

// Render returns the full generated TypeScript module.
func Render() (string, error) {
	cfg := config.Default()
	var b strings.Builder

	b.WriteString("// Code generated by internal/webvocab. DO NOT EDIT.\n")
	b.WriteString("// Regenerate with `task codegen`.\n")
	b.WriteString("//\n")
	b.WriteString("// The compiled-in vocabulary, rendered from the Go definitions\n")
	b.WriteString("// (internal/config, internal/nibtypes, internal/estimate). The committed\n")
	b.WriteString("// file is pinned byte-for-byte by TestGeneratedVocabularyIsFresh.\n\n")

	// A role added to roleNames reaches the StatusRole union on regeneration,
	// and the web's exhaustive StatusRole switches fail svelte-check until they
	// classify it.
	names := make([]string, len(roleNames))
	for i, r := range roleNames {
		names[i] = fmt.Sprintf("%q", r.String())
	}
	b.WriteString("/** A status's lifecycle role — the Go config.Role enum. */\n")
	b.WriteString("export type StatusRole = " + strings.Join(names, " | ") + ";\n\n")

	b.WriteString("/** Statuses in rank order (Go config.DefaultStatuses) — the sort priority lists use. */\n")
	b.WriteString("export const STATUS_DEFS: readonly { readonly name: string; readonly role: StatusRole }[] = [\n")
	for _, s := range config.DefaultStatuses {
		if !knownRole(s.Role) {
			return "", fmt.Errorf("status %q carries role %v, which the generator does not know how to spell — classify it in roleNames and in every StatusRole switch", s.Name, s.Role)
		}
		fmt.Fprintf(&b, "  { name: %q, role: %q },\n", s.Name, s.Role.String())
	}
	b.WriteString("];\n\n")

	b.WriteString("/** Statuses in workflow (transition) order — the order choosers list. */\n")
	writeStringArray(&b, "STATUS_WORKFLOW_ORDER", cfg.WorkflowStatusNames())

	b.WriteString("/** Status-group names shared with the CLI: `-s open` is `status:open`. */\n")
	fmt.Fprintf(&b, "export const STATUS_GROUP_OPEN = %q;\n", config.StatusGroupOpen)
	fmt.Fprintf(&b, "export const STATUS_GROUP_CLOSED = %q;\n\n", config.StatusGroupClosed)

	writeStringArray(&b, "TYPES", typeNames())

	b.WriteString("/** Parent type → legal child types (Go nibtypes.ValidChildTypes). */\n")
	b.WriteString("export const VALID_CHILD_TYPES: Record<string, readonly string[]> = {\n")
	for _, t := range typeNames() {
		children := nibtypes.ValidChildTypes(t)
		quoted := make([]string, len(children))
		for i, c := range children {
			quoted[i] = fmt.Sprintf("%q", c)
		}
		fmt.Fprintf(&b, "  %s: [%s],\n", t, strings.Join(quoted, ", "))
	}
	b.WriteString("};\n\n")

	b.WriteString("/** Container→leaf rank derived from the hierarchy: a leaf ranks 0, a container one above its highest child. Milestone is pinned above every container so the Epics and Features lenses HIDE a milestone row rather than sweeping it into their leftover. */\n")
	b.WriteString("export const TYPE_RANK: Record<string, number> = {\n")
	ranks := typeRanks()
	for _, t := range typeNames() {
		fmt.Fprintf(&b, "  %s: %d,\n", t, ranks[t])
	}
	b.WriteString("};\n\n")

	writeStringArray(&b, "PRIORITIES", priorityNames())

	b.WriteString("/** Estimates with their point weights and display labels. */\n")
	b.WriteString("export const ESTIMATE_DEFS: readonly { readonly name: string; readonly weight: number; readonly label: string }[] = [\n")
	for _, e := range config.DefaultEstimates {
		fmt.Fprintf(&b, "  { name: %q, weight: %d, label: %q },\n", e.Name, estimate.Weight(e.Name), estimateLabel(e.Name))
	}
	b.WriteString("];\n\n")

	b.WriteString("/** Creation defaults (Go config defaults for a new nib). */\n")
	fmt.Fprintf(&b, "export const DEFAULT_STATUS = %q;\n", cfg.Nibs.DefaultStatus)
	fmt.Fprintf(&b, "export const DEFAULT_TYPE = %q;\n", cfg.Nibs.DefaultType)

	return b.String(), nil
}

func knownRole(r config.Role) bool {
	for _, k := range roleNames {
		if r == k {
			return true
		}
	}
	return false
}

func writeStringArray(b *strings.Builder, name string, values []string) {
	quoted := make([]string, len(values))
	for i, v := range values {
		quoted[i] = fmt.Sprintf("%q", v)
	}
	fmt.Fprintf(b, "export const %s: readonly string[] = [%s];\n\n", name, strings.Join(quoted, ", "))
}

func typeNames() []string {
	names := make([]string, len(config.DefaultTypes))
	for i, t := range config.DefaultTypes {
		names[i] = t.Name
	}
	return names
}

func priorityNames() []string {
	names := make([]string, len(config.DefaultPriorities))
	for i, p := range config.DefaultPriorities {
		names[i] = p.Name
	}
	return names
}

// typeRanks derives each type's container→leaf rank from the hierarchy: a type
// with no legal children ranks 0, a container one above its highest-ranked
// child. The recursion assumes the hierarchy is acyclic.
//
// Milestone takes no children, so it would rank 0; it is pinned above every
// container instead. A type lens (typeLens in web/src/lib/viewSpine.ts) hides
// only rows ranked above its tier, so a rank-0 milestone would fall into the
// lens's leftover section, such as "No epic".
func typeRanks() map[string]int {
	ranks := make(map[string]int, len(config.DefaultTypes))
	var rank func(t string) int
	rank = func(t string) int {
		if r, ok := ranks[t]; ok {
			return r
		}
		max := -1
		for _, c := range nibtypes.ValidChildTypes(t) {
			if r := rank(c); r > max {
				max = r
			}
		}
		ranks[t] = max + 1
		return ranks[t]
	}
	for _, t := range typeNames() {
		rank(t)
	}
	top := 0
	for t, r := range ranks {
		if t != "milestone" && r > top {
			top = r
		}
	}
	ranks["milestone"] = top + 1
	return ranks
}

// estimateLabel returns the part of an estimate's description before " (", e.g.
// "Small" from "Small (1 point)".
func estimateLabel(name string) string {
	for _, e := range config.DefaultEstimates {
		if e.Name == name {
			label, _, _ := strings.Cut(e.Description, " (")
			return strings.TrimSpace(label)
		}
	}
	return name
}
