// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/99designs/gqlgen/graphql"
	"github.com/alphaleonis/nibs/internal/nib"
)

// Structured body modifications applied atomically.
// Operations are applied in order: all replacements sequentially, then append.
// If any operation fails, the entire mutation fails (transactional).
type BodyModification struct {
	// Text replacements applied sequentially in array order.
	// Each old text must match exactly once at the time it's applied.
	Replace []*ReplaceOperation `json:"replace,omitempty"`
	// Text to append after all replacements.
	// Appended with blank line separator.
	Append *string `json:"append,omitempty"`
}

// A per-child ETag pair for optimistic concurrency in bulk reorder mutations.
// Each entry's `etag` is pre-checked against the on-disk content of `id`
// before any writes; a pre-validation mismatch aborts the operation
// atomically. Per-nib writes are then issued sequentially; a concurrent
// modification between pre-validation and the per-nib write surfaces as
// ETagMismatchError for that nib, leaving prior writes in this batch
// persisted (matching single-nib reorderNib semantics).
//
// Both mismatches — the pre-validation one and the racing one — carry
// extensions.code = "ETAG_MISMATCH", so a GraphQL client can route either
// conflict structurally rather than on message text, and both name the
// offending nib the same way ("failed to reorder <id>: etag mismatch: …") so
// the conflict's current etag is attributable to one nib. The code does NOT
// distinguish them, and they differ in durability (see above): a client that
// must know whether part of the batch landed has to re-read the affected nibs
// rather than infer it from the code.
type ChildEtag struct {
	ID   string `json:"id"`
	Etag string `json:"etag"`
}

type Config struct {
	// Project name derived from the config file directory
	ProjectName string `json:"projectName"`
	// Configured nib ID prefix (e.g., 'nibs-', 'myproj-'). Empty if unset.
	Prefix string `json:"prefix"`
}

// Input for creating a new nib
type CreateNibInput struct {
	// Nib title (required)
	Title string `json:"title"`
	// Nib type (defaults to 'task')
	Type *string `json:"type,omitempty"`
	// Status (defaults to 'todo')
	Status *string `json:"status,omitempty"`
	// Priority level (defaults to 'normal')
	Priority *string `json:"priority,omitempty"`
	// Estimate size (s, m, l, xl)
	Estimate *string `json:"estimate,omitempty"`
	// Tags for categorization
	Tags []string `json:"tags,omitempty"`
	// Markdown body content
	Body *string `json:"body,omitempty"`
	// Parent nib ID (validated against type hierarchy)
	Parent *string `json:"parent,omitempty"`
	// Nib IDs this nib is blocking
	Blocking []string `json:"blocking,omitempty"`
	// Nib IDs that are blocking this nib
	BlockedBy []string `json:"blockedBy,omitempty"`
	// Linked document paths (repo-root-relative)
	Documents []string `json:"documents,omitempty"`
	// Custom ID prefix (overrides config prefix for this nib)
	Prefix *string `json:"prefix,omitempty"`
	// Insert after this sibling nib ID (mutually exclusive with beforeId, first)
	AfterID *string `json:"afterId,omitempty"`
	// Insert before this sibling nib ID (mutually exclusive with afterId, first)
	BeforeID *string `json:"beforeId,omitempty"`
	// Insert before all siblings (mutually exclusive with afterId, beforeId)
	First *bool `json:"first,omitempty"`
}

// A batch is not atomic. Root mutation fields execute serially in document
// order, execution does not stop at the first failure, and each field commits
// on its own — so a response that reports failure can still have written
// durable edits. Re-read any nib the batch named rather than trusting an etag
// cached before the call.
//
// Which fields committed is not carried on the wire. The `nibs graphql` CLI
// renders it into the failure message when it can name at least one, but that
// `succeeded` list is a lower bound on what landed rather than an accounting:
// an error anywhere inside a field's own selection marks that field failed even
// when its write committed. Over HTTP there is no such list at all — read the
// error paths against the fields the document sent. The fuller treatment is in
// the agent guide (`nibs prime --full`, cmd/prompt-full.tmpl).
type Mutation struct {
}

// A change event emitted when a nib is created, updated, deleted, or archived.
type NibChangeEvent struct {
	// The type of change: created, updated, deleted, or archived. An archived nib
	// still exists — it moved to the archive directory and remains readable and
	// updatable there — so archived is reported separately from deleted.
	Type string `json:"type"`
	// The ID of the affected nib (always present, even for deletes)
	NibID string `json:"nibId"`
	// The nib after the change (null for deleted events)
	Nib *nib.Nib `json:"nib,omitempty"`
}

// Filter options for querying nibs
type NibFilter struct {
	// Full-text search across slug, title, and body using Bleve query syntax.
	//
	// Single-token queries that look like a nib ID or ID fragment also match
	// directly by ID: a substring of the short ID (at least 2 characters), a
	// prefix of the full ID (starting with the configured prefix), or an exact
	// full ID, case-insensitive, surrounding whitespace trimmed.
	// When no sort is given, ID matches are returned first, followed by
	// full-text hits in relevance order; an explicit sort overrides this
	// ordering.
	//
	// Examples:
	// - "login" - exact term match
	// - "login~" - fuzzy match (1 edit distance)
	// - "login~2" - fuzzy match (2 edit distance)
	// - "log*" - wildcard prefix
	// - "\"user login\"" - exact phrase
	// - "user AND login" - both terms required
	// - "user OR login" - either term
	// - "slug:auth" - search only slug field
	// - "title:login" - search only title field
	// - "body:auth" - search only body field
	// - "5a8k" - also matches nibs whose ID contains "5a8k"
	//
	// An empty string leaves it unfiltered, the opposite of the id-valued fields
	// such as parentId: "no keyword filter" is a real meaning, so `search: "$q"`
	// with an empty q is a reasonable thing to write. There is no nib whose id is
	// "", which is why the same value is a refusal there.
	//
	// On a relationship field (children, blockedBy, blocking, mentions,
	// mentionedBy) the term INTERSECTS that relationship instead of choosing the
	// nibs to consider: `children(filter: {search: "auth"})` means "the children of
	// this nib that match auth", and a match that is not a child of it is not in
	// the answer. Two consequences follow from that, both differences from the
	// top-level nibs query. A relationship field never returns a nib outside the
	// relation, so it does not add the ancestors of its matches — tree completion
	// belongs to a query over the whole store. And relevance ordering does not
	// apply: the field keeps its own order (children stay in order key order),
	// since the term selects rather than ranks.
	//
	// WHICH answer the index is asked for follows from what bounds the query, not
	// from which surface asks. A term selecting from the whole store is CAPPED: the
	// index answers with at most 1000 hits per leg (id matches and full-text hits are
	// capped separately) and that truncation IS the answer — the top hits for the
	// term. A term intersected with a set something else already bounds is UNCAPPED,
	// because a store-wide cap there would truncate the store rather than the answer,
	// dropping a genuine member that ranks below the global cutoff.
	//
	// Concretely, on the top-level nibs query: the term alone is capped, and so is
	// the term alongside any of the list and tri-state facets — status, excludeStatus,
	// type, excludeType, priority, excludePriority, estimate, excludeEstimate, tags,
	// excludeTags, hasParent, hasBlocking, isBlocked, hasBlockedBy. None of those
	// names a nib, so the population they narrow is still the store. Combining the
	// term with a field that DOES name one — parentId, ancestorId, descendantId,
	// siblingId, blockingId, blockedById, mentionsId, mentionedById — makes the read
	// uncapped. Every relationship field (children, blockedBy, blocking, mentions,
	// mentionedBy) is uncapped for the same reason: the relation it names is the
	// bound.
	//
	// So `nibs(filter: {search: q, parentId: X})` and
	// `nib(id: X) { children(filter: {search: q}) }` agree on the MATCHES. They are
	// still not the same response: the top-level query completes the tree with those
	// matches' ancestors, X included, and a relationship field does not.
	Search *string `json:"search,omitempty"`
	// Include only nibs with these statuses (OR logic)
	Status []string `json:"status,omitempty"`
	// Exclude nibs with these statuses
	ExcludeStatus []string `json:"excludeStatus,omitempty"`
	// Include only nibs with these types (OR logic)
	Type []string `json:"type,omitempty"`
	// Exclude nibs with these types
	ExcludeType []string `json:"excludeType,omitempty"`
	// Include only nibs with these priorities (OR logic)
	Priority []string `json:"priority,omitempty"`
	// Exclude nibs with these priorities
	ExcludePriority []string `json:"excludePriority,omitempty"`
	// Include only nibs with these estimates (OR logic)
	Estimate []string `json:"estimate,omitempty"`
	// Exclude nibs with these estimates
	ExcludeEstimate []string `json:"excludeEstimate,omitempty"`
	// Include only nibs with any of these tags (OR logic)
	Tags []string `json:"tags,omitempty"`
	// Exclude nibs with any of these tags
	ExcludeTags []string `json:"excludeTags,omitempty"`
	// Tri-state: true keeps nibs whose parent link resolves to a nib, false keeps
	// exactly the ones with no parent, null does not filter. A nib whose parent link
	// names no nib counts as parentless, matching how the parent field, parentId and
	// siblingId treat it. Such a nib still reports its unresolvable link under
	// storedParentId, which is not a parent and does not affect this filter.
	//
	// Combining false with the parentId FILTER is refused: no nib both has a given
	// parent and has none. See parentId.
	HasParent *bool `json:"hasParent,omitempty"`
	// Include only nibs with this specific parent ID.
	//
	// Matches on the RESOLVED parent, the same reading the parentId field and
	// hasParent give: a nib whose link is stored in short form matches the full id
	// it resolves to, and a link naming no nib matches nothing. Filtering on the
	// raw stored spelling is not offered — storedParentId is an inspection field,
	// not a filter.
	//
	// An id naming no nib is refused with a NOT_FOUND error rather than matching
	// nothing, so a mistyped or stale id stays distinguishable from a genuine empty
	// result. An empty string is refused as a malformed argument: it names no nib
	// and never could. Unlike the not-found refusal above it carries no
	// extensions.code, so a GraphQL client sees a generic error; the CLI reports
	// VALIDATION_ERROR (exit 2). Omit the field to leave it unfiltered, or use
	// hasParent: false to select the nibs that have no parent.
	//
	// Combining it with hasParent: false is refused as a malformed argument
	// (VALIDATION_ERROR, exit 2), and refused BEFORE the id is looked up, so the
	// pair is reported even when the id also names no nib: every nib this field
	// matches has a parent, so no store state satisfies both halves and correcting
	// the id would not make the query answerable. Unlike the empty-id refusal above
	// it carries extensions.code = "FILTER_CONTRADICTION", so a GraphQL client can
	// route it structurally rather than on message text. The exception is the EMPTY
	// string, which keeps the empty-id refusal above — the same class and exit, but
	// uncoded, and its message redirects to hasParent: false, the filter that does
	// select parentless nibs. The flag surface refuses
	// `nibs list --parent X --no-parent` with the same exit status.
	ParentID *string `json:"parentId,omitempty"`
	// Include only nibs with this specific nib ID somewhere in their parent chain
	// (that nib's descendants at any depth). This filter excludes the nib itself.
	// On the top-level nibs query, combining it with search adds it back, because
	// that query completes the tree with every match's ancestors. A relationship
	// field does not complete the tree, so there the target stays excluded — see
	// search.
	//
	// An id naming no nib is refused with a NOT_FOUND error rather than matching
	// nothing, so a mistyped or stale id stays distinguishable from a genuine empty
	// result. An empty string is refused as a malformed argument: it names no nib
	// and never could. Unlike the not-found refusal above it carries no
	// extensions.code, so a GraphQL client sees a generic error; the CLI reports
	// VALIDATION_ERROR (exit 2). Omit the field to leave it unfiltered.
	AncestorID *string `json:"ancestorId,omitempty"`
	// Include only nibs with this specific nib ID somewhere in their descendant
	// subtree (that nib's ancestor chain, itself excluded).
	//
	// An id naming no nib is refused with a NOT_FOUND error rather than matching
	// nothing, so a mistyped or stale id stays distinguishable from a genuine empty
	// result. An empty string is refused as a malformed argument: it names no nib
	// and never could. Unlike the not-found refusal above it carries no
	// extensions.code, so a GraphQL client sees a generic error; the CLI reports
	// VALIDATION_ERROR (exit 2). Omit the field to leave it unfiltered.
	DescendantID *string `json:"descendantId,omitempty"`
	// Include only nibs sharing this specific nib's parent, or the other root nibs
	// when it has no parent (itself excluded). On the top-level nibs query,
	// combining it with search also brings in the shared parent, because that query
	// completes the tree with every match's ancestors. A relationship field does not
	// complete the tree, so there the shared parent stays out — see search.
	//
	// An id naming no nib is refused with a NOT_FOUND error rather than matching
	// nothing, so a mistyped or stale id stays distinguishable from a genuine empty
	// result. An empty string is refused as a malformed argument: it names no nib
	// and never could. Unlike the not-found refusal above it carries no
	// extensions.code, so a GraphQL client sees a generic error; the CLI reports
	// VALIDATION_ERROR (exit 2). Omit the field to leave it unfiltered.
	SiblingID *string `json:"siblingId,omitempty"`
	// Tri-state: true keeps nibs that are ACTIVELY blocking others, false keeps
	// exactly the rest, null does not filter. A blocker whose status released its
	// dependents (completed, scrapped) is not actively blocking anything, so it is
	// in the false set even while other nibs still list it in their blocked_by.
	//
	// Combining false with blockingId is therefore a real query rather than a
	// contradiction — see blockingId.
	HasBlocking *bool `json:"hasBlocking,omitempty"`
	// Include only nibs that are blocking this specific nib ID.
	//
	// Membership is the target's stored blocked_by, whatever the candidate's status,
	// which is what makes `blockingId: X, hasBlocking: false` meaningful: it selects
	// the blockers X still lists that are no longer blocking anything — either
	// because their own status released their dependents, or because every nib that
	// listed them, X included, has itself been released. The second case is why the
	// pair can return an OPEN blocker: X completed, its todo blocker listed nowhere
	// else, and that blocker is in the answer. That pair is answered, not refused;
	// hasBlocking: true selects the ones still blocking.
	//
	// An id naming no nib is refused with a NOT_FOUND error rather than matching
	// nothing, so a mistyped or stale id stays distinguishable from a genuine empty
	// result. An empty string is refused as a malformed argument: it names no nib
	// and never could. Unlike the not-found refusal above it carries no
	// extensions.code, so a GraphQL client sees a generic error; the CLI reports
	// VALIDATION_ERROR (exit 2). Omit the field to leave it unfiltered.
	BlockingID *string `json:"blockingId,omitempty"`
	// Tri-state: true keeps nibs blocked by others (via incoming blocking links or blocked_by field), false keeps exactly the unblocked ones, null does not filter
	IsBlocked *bool `json:"isBlocked,omitempty"`
	// Tri-state: true keeps nibs that have explicit blocked_by entries, false keeps
	// exactly those with none, null does not filter.
	//
	// Combining false with the blockedById FILTER is refused: no nib both lists a
	// given blocker and lists none. See blockedById.
	HasBlockedBy *bool `json:"hasBlockedBy,omitempty"`
	// Include only nibs blocked by this specific nib ID (via blocked_by field).
	//
	// An id naming no nib is refused with a NOT_FOUND error rather than matching
	// nothing, so a mistyped or stale id stays distinguishable from a genuine empty
	// result. An empty string is refused as a malformed argument: it names no nib
	// and never could. Unlike the not-found refusal above it carries no
	// extensions.code, so a GraphQL client sees a generic error; the CLI reports
	// VALIDATION_ERROR (exit 2). Omit the field to leave it unfiltered.
	//
	// Combining it with hasBlockedBy: false is refused as a malformed argument
	// (VALIDATION_ERROR, exit 2), and refused BEFORE the id is looked up, so the
	// pair is reported even when the id also names no nib: matching this field
	// requires a blocked_by entry, so no store state satisfies both halves. Unlike
	// the empty-id refusal above it carries extensions.code = "FILTER_CONTRADICTION",
	// so a GraphQL client can route it structurally rather than on message text. The
	// exception is the EMPTY string, which keeps the empty-id refusal above — the
	// same class and exit, but uncoded, reported as malformed input rather than as
	// the pair.
	BlockedByID *string `json:"blockedById,omitempty"`
	// Include only nibs that mention this specific nib ID in their body.
	//
	// An id naming no nib is refused with a NOT_FOUND error rather than matching
	// nothing, so a mistyped or stale id stays distinguishable from a genuine empty
	// result. An empty string is refused as a malformed argument: it names no nib
	// and never could. Unlike the not-found refusal above it carries no
	// extensions.code, so a GraphQL client sees a generic error; the CLI reports
	// VALIDATION_ERROR (exit 2). Omit the field to leave it unfiltered.
	MentionsID *string `json:"mentionsId,omitempty"`
	// Include only nibs mentioned in the given nib's body.
	//
	// An id naming no nib is refused with a NOT_FOUND error rather than matching
	// nothing, so a mistyped or stale id stays distinguishable from a genuine empty
	// result. An empty string is refused as a malformed argument: it names no nib
	// and never could. Unlike the not-found refusal above it carries no
	// extensions.code, so a GraphQL client sees a generic error; the CLI reports
	// VALIDATION_ERROR (exit 2). Omit the field to leave it unfiltered.
	MentionedByID *string `json:"mentionedById,omitempty"`
}

// Sort options for nib queries
type NibSort struct {
	// Field to sort by
	Field NibSortField `json:"field"`
	// Sort direction (defaults to ASC)
	Direction *SortDirection `json:"direction,omitempty"`
}

type Query struct {
}

// A single text replacement operation.
type ReplaceOperation struct {
	// Text to find (must occur exactly once, cannot be empty)
	Old string `json:"old"`
	// Replacement text (can be empty to delete the matched text)
	New string `json:"new"`
}

type Subscription struct {
}

// Input for updating an existing nib
type UpdateNibInput struct {
	// New title. Not a clearable field: null/omit both leave the title unchanged
	// (a title is required, so it is never cleared).
	Title *string `json:"title,omitempty"`
	// New status. Not a clearable field: null/omit both leave the status unchanged.
	Status *string `json:"status,omitempty"`
	// New type. Not a clearable field: null/omit both leave the type unchanged.
	Type *string `json:"type,omitempty"`
	// New priority. Explicit null clears the priority; omit to leave it unchanged.
	// Note: a cleared priority reads back as the effective default "normal" (the
	// data model treats empty as normal), so the clear is not observable on read.
	Priority graphql.Omittable[*string] `json:"priority,omitempty"`
	// New estimate size (s, m, l, xl). Explicit null clears the estimate; omit to
	// leave it unchanged.
	Estimate graphql.Omittable[*string] `json:"estimate,omitempty"`
	// Replace all tags. An empty list clears all tags; omit (null) to leave the
	// existing tags unchanged. Mutually exclusive with addTags/removeTags.
	Tags []string `json:"tags,omitempty"`
	// Add tags to existing list
	AddTags []string `json:"addTags,omitempty"`
	// Remove tags from existing list
	RemoveTags []string `json:"removeTags,omitempty"`
	// New body content (full replacement, mutually exclusive with bodyMod)
	Body *string `json:"body,omitempty"`
	// Structured body modifications (mutually exclusive with body)
	BodyMod *BodyModification `json:"bodyMod,omitempty"`
	// Set the parent nib ID (validated against the type hierarchy). Explicit null
	// OR empty string clears the parent (moves the nib to root); omit to leave it
	// unchanged.
	Parent graphql.Omittable[*string] `json:"parent,omitempty"`
	// Add nibs to blocking list (validates cycles and existence)
	AddBlocking []string `json:"addBlocking,omitempty"`
	// Remove nibs from blocking list
	RemoveBlocking []string `json:"removeBlocking,omitempty"`
	// Add nibs to blocked-by list (validates cycles and existence)
	AddBlockedBy []string `json:"addBlockedBy,omitempty"`
	// Remove nibs from blocked-by list
	RemoveBlockedBy []string `json:"removeBlockedBy,omitempty"`
	// Replace all documents (nil preserves existing, mutually exclusive with addDocuments/removeDocuments)
	Documents []string `json:"documents,omitempty"`
	// Add document paths to existing list
	AddDocuments []string `json:"addDocuments,omitempty"`
	// Remove document paths from existing list
	RemoveDocuments []string `json:"removeDocuments,omitempty"`
	// ETag for optimistic concurrency control (optional)
	IfMatch *string `json:"ifMatch,omitempty"`
}

// Result of the best-effort check for a newer nibs release.
type UpdateStatus struct {
	// The running server version (e.g. "v0.5.1"); empty for a dev build.
	Current string `json:"current"`
	// The latest released version (e.g. "v0.6.0"); empty if unknown.
	Latest string `json:"latest"`
	// True when a newer release than the running version is available.
	UpdateAvailable bool `json:"updateAvailable"`
}

// Sort field for nib queries
type NibSortField string

const (
	NibSortFieldOrder          NibSortField = "ORDER"
	NibSortFieldCreatedAt      NibSortField = "CREATED_AT"
	NibSortFieldUpdatedAt      NibSortField = "UPDATED_AT"
	NibSortFieldTitle          NibSortField = "TITLE"
	NibSortFieldPriority       NibSortField = "PRIORITY"
	NibSortFieldID             NibSortField = "ID"
	NibSortFieldStatus         NibSortField = "STATUS"
	NibSortFieldStatusPriority NibSortField = "STATUS_PRIORITY"
)

var AllNibSortField = []NibSortField{
	NibSortFieldOrder,
	NibSortFieldCreatedAt,
	NibSortFieldUpdatedAt,
	NibSortFieldTitle,
	NibSortFieldPriority,
	NibSortFieldID,
	NibSortFieldStatus,
	NibSortFieldStatusPriority,
}

func (e NibSortField) IsValid() bool {
	switch e {
	case NibSortFieldOrder, NibSortFieldCreatedAt, NibSortFieldUpdatedAt, NibSortFieldTitle, NibSortFieldPriority, NibSortFieldID, NibSortFieldStatus, NibSortFieldStatusPriority:
		return true
	}
	return false
}

func (e NibSortField) String() string {
	return string(e)
}

func (e *NibSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NibSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NibSortField", str)
	}
	return nil
}

func (e NibSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NibSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NibSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Sort direction
type SortDirection string

const (
	SortDirectionAsc  SortDirection = "ASC"
	SortDirectionDesc SortDirection = "DESC"
)

var AllSortDirection = []SortDirection{
	SortDirectionAsc,
	SortDirectionDesc,
}

func (e SortDirection) IsValid() bool {
	switch e {
	case SortDirectionAsc, SortDirectionDesc:
		return true
	}
	return false
}

func (e SortDirection) String() string {
	return string(e)
}

func (e *SortDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortDirection", str)
	}
	return nil
}

func (e SortDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
