// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/alphaleonis/nibs/internal/nib"
)

// Structured body modifications applied atomically.
// Operations are applied in order: all replacements sequentially, then append.
// If any operation fails, the entire mutation fails (transactional).
type BodyModification struct {
	// Text replacements applied sequentially in array order.
	// Each old text must match exactly once at the time it's applied.
	Replace []*ReplaceOperation `json:"replace,omitempty"`
	// Text to append after all replacements.
	// Appended with blank line separator.
	Append *string `json:"append,omitempty"`
}

// A per-child ETag pair for optimistic concurrency in bulk reorder mutations.
// Each entry's `etag` is pre-checked against the on-disk content of `id`
// before any writes; a pre-validation mismatch aborts the operation
// atomically. Per-nib writes are then issued sequentially; a concurrent
// modification between pre-validation and the per-nib write surfaces as
// ETagMismatchError for that nib, leaving prior writes in this batch
// persisted (matching single-nib reorderNib semantics).
type ChildEtag struct {
	ID   string `json:"id"`
	Etag string `json:"etag"`
}

type Config struct {
	// Project name derived from the config file directory
	ProjectName string `json:"projectName"`
	// Configured nib ID prefix (e.g., 'nibs-', 'myproj-'). Empty if unset.
	Prefix string `json:"prefix"`
}

// Input for creating a new nib
type CreateNibInput struct {
	// Nib title (required)
	Title string `json:"title"`
	// Nib type (defaults to 'task')
	Type *string `json:"type,omitempty"`
	// Status (defaults to 'todo')
	Status *string `json:"status,omitempty"`
	// Priority level (defaults to 'normal')
	Priority *string `json:"priority,omitempty"`
	// Estimate size (s, m, l, xl)
	Estimate *string `json:"estimate,omitempty"`
	// Tags for categorization
	Tags []string `json:"tags,omitempty"`
	// Markdown body content
	Body *string `json:"body,omitempty"`
	// Parent nib ID (validated against type hierarchy)
	Parent *string `json:"parent,omitempty"`
	// Nib IDs this nib is blocking
	Blocking []string `json:"blocking,omitempty"`
	// Nib IDs that are blocking this nib
	BlockedBy []string `json:"blockedBy,omitempty"`
	// Linked document paths (repo-root-relative)
	Documents []string `json:"documents,omitempty"`
	// Custom ID prefix (overrides config prefix for this nib)
	Prefix *string `json:"prefix,omitempty"`
	// Insert after this sibling nib ID (mutually exclusive with beforeId, first)
	AfterID *string `json:"afterId,omitempty"`
	// Insert before this sibling nib ID (mutually exclusive with afterId, first)
	BeforeID *string `json:"beforeId,omitempty"`
	// Insert before all siblings (mutually exclusive with afterId, beforeId)
	First *bool `json:"first,omitempty"`
}

type Mutation struct {
}

// A change event emitted when a nib is created, updated, or deleted.
type NibChangeEvent struct {
	// The type of change: created, updated, or deleted
	Type string `json:"type"`
	// The ID of the affected nib (always present, even for deletes)
	NibID string `json:"nibId"`
	// The nib after the change (null for deleted events)
	Nib *nib.Nib `json:"nib,omitempty"`
}

// Filter options for querying nibs
type NibFilter struct {
	// Full-text search across slug, title, and body using Bleve query syntax.
	//
	// Examples:
	// - "login" - exact term match
	// - "login~" - fuzzy match (1 edit distance)
	// - "login~2" - fuzzy match (2 edit distance)
	// - "log*" - wildcard prefix
	// - "\"user login\"" - exact phrase
	// - "user AND login" - both terms required
	// - "user OR login" - either term
	// - "slug:auth" - search only slug field
	// - "title:login" - search only title field
	// - "body:auth" - search only body field
	Search *string `json:"search,omitempty"`
	// Include only nibs with these statuses (OR logic)
	Status []string `json:"status,omitempty"`
	// Exclude nibs with these statuses
	ExcludeStatus []string `json:"excludeStatus,omitempty"`
	// Include only nibs with these types (OR logic)
	Type []string `json:"type,omitempty"`
	// Exclude nibs with these types
	ExcludeType []string `json:"excludeType,omitempty"`
	// Include only nibs with these priorities (OR logic)
	Priority []string `json:"priority,omitempty"`
	// Exclude nibs with these priorities
	ExcludePriority []string `json:"excludePriority,omitempty"`
	// Include only nibs with these estimates (OR logic)
	Estimate []string `json:"estimate,omitempty"`
	// Exclude nibs with these estimates
	ExcludeEstimate []string `json:"excludeEstimate,omitempty"`
	// Include only nibs with any of these tags (OR logic)
	Tags []string `json:"tags,omitempty"`
	// Exclude nibs with any of these tags
	ExcludeTags []string `json:"excludeTags,omitempty"`
	// Include only nibs with a parent
	HasParent *bool `json:"hasParent,omitempty"`
	// Include only nibs with this specific parent ID
	ParentID *string `json:"parentId,omitempty"`
	// Include only nibs that are blocking other nibs
	HasBlocking *bool `json:"hasBlocking,omitempty"`
	// Include only nibs that are blocking this specific nib ID
	BlockingID *string `json:"blockingId,omitempty"`
	// Include only nibs that are blocked by others (via incoming blocking links or blocked_by field)
	IsBlocked *bool `json:"isBlocked,omitempty"`
	// Include only nibs that have explicit blocked-by entries
	HasBlockedBy *bool `json:"hasBlockedBy,omitempty"`
	// Include only nibs blocked by this specific nib ID (via blocked_by field)
	BlockedByID *string `json:"blockedById,omitempty"`
	// Exclude nibs that have a parent
	NoParent *bool `json:"noParent,omitempty"`
	// Exclude nibs that are blocking other nibs
	NoBlocking *bool `json:"noBlocking,omitempty"`
	// Exclude nibs that have explicit blocked-by entries
	NoBlockedBy *bool `json:"noBlockedBy,omitempty"`
	// Include only nibs that mention this specific nib ID in their body
	MentionsID *string `json:"mentionsId,omitempty"`
	// Include only nibs mentioned in the given nib's body
	MentionedByID *string `json:"mentionedById,omitempty"`
}

// Sort options for nib queries
type NibSort struct {
	// Field to sort by
	Field NibSortField `json:"field"`
	// Sort direction (defaults to ASC)
	Direction *SortDirection `json:"direction,omitempty"`
}

type Query struct {
}

// A single text replacement operation.
type ReplaceOperation struct {
	// Text to find (must occur exactly once, cannot be empty)
	Old string `json:"old"`
	// Replacement text (can be empty to delete the matched text)
	New string `json:"new"`
}

type Subscription struct {
}

// Input for updating an existing nib
type UpdateNibInput struct {
	// New title
	Title *string `json:"title,omitempty"`
	// New status
	Status *string `json:"status,omitempty"`
	// New type
	Type *string `json:"type,omitempty"`
	// New priority
	Priority *string `json:"priority,omitempty"`
	// New estimate size (s, m, l, xl, or null to clear)
	Estimate *string `json:"estimate,omitempty"`
	// Replace all tags (nil preserves existing, mutually exclusive with addTags/removeTags)
	Tags []string `json:"tags,omitempty"`
	// Add tags to existing list
	AddTags []string `json:"addTags,omitempty"`
	// Remove tags from existing list
	RemoveTags []string `json:"removeTags,omitempty"`
	// New body content (full replacement, mutually exclusive with bodyMod)
	Body *string `json:"body,omitempty"`
	// Structured body modifications (mutually exclusive with body)
	BodyMod *BodyModification `json:"bodyMod,omitempty"`
	// Set parent nib ID (null/empty to clear, validates type hierarchy)
	Parent *string `json:"parent,omitempty"`
	// Add nibs to blocking list (validates cycles and existence)
	AddBlocking []string `json:"addBlocking,omitempty"`
	// Remove nibs from blocking list
	RemoveBlocking []string `json:"removeBlocking,omitempty"`
	// Add nibs to blocked-by list (validates cycles and existence)
	AddBlockedBy []string `json:"addBlockedBy,omitempty"`
	// Remove nibs from blocked-by list
	RemoveBlockedBy []string `json:"removeBlockedBy,omitempty"`
	// Replace all documents (nil preserves existing, mutually exclusive with addDocuments/removeDocuments)
	Documents []string `json:"documents,omitempty"`
	// Add document paths to existing list
	AddDocuments []string `json:"addDocuments,omitempty"`
	// Remove document paths from existing list
	RemoveDocuments []string `json:"removeDocuments,omitempty"`
	// ETag for optimistic concurrency control (optional)
	IfMatch *string `json:"ifMatch,omitempty"`
}

// Sort field for nib queries
type NibSortField string

const (
	NibSortFieldOrder          NibSortField = "ORDER"
	NibSortFieldCreatedAt      NibSortField = "CREATED_AT"
	NibSortFieldUpdatedAt      NibSortField = "UPDATED_AT"
	NibSortFieldTitle          NibSortField = "TITLE"
	NibSortFieldPriority       NibSortField = "PRIORITY"
	NibSortFieldID             NibSortField = "ID"
	NibSortFieldStatus         NibSortField = "STATUS"
	NibSortFieldStatusPriority NibSortField = "STATUS_PRIORITY"
)

var AllNibSortField = []NibSortField{
	NibSortFieldOrder,
	NibSortFieldCreatedAt,
	NibSortFieldUpdatedAt,
	NibSortFieldTitle,
	NibSortFieldPriority,
	NibSortFieldID,
	NibSortFieldStatus,
	NibSortFieldStatusPriority,
}

func (e NibSortField) IsValid() bool {
	switch e {
	case NibSortFieldOrder, NibSortFieldCreatedAt, NibSortFieldUpdatedAt, NibSortFieldTitle, NibSortFieldPriority, NibSortFieldID, NibSortFieldStatus, NibSortFieldStatusPriority:
		return true
	}
	return false
}

func (e NibSortField) String() string {
	return string(e)
}

func (e *NibSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NibSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NibSortField", str)
	}
	return nil
}

func (e NibSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NibSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NibSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Sort direction
type SortDirection string

const (
	SortDirectionAsc  SortDirection = "ASC"
	SortDirectionDesc SortDirection = "DESC"
)

var AllSortDirection = []SortDirection{
	SortDirectionAsc,
	SortDirectionDesc,
}

func (e SortDirection) IsValid() bool {
	switch e {
	case SortDirectionAsc, SortDirectionDesc:
		return true
	}
	return false
}

func (e SortDirection) String() string {
	return string(e)
}

func (e *SortDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortDirection", str)
	}
	return nil
}

func (e SortDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
