package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"errors"
	"fmt"

	"github.com/alphaleonis/nibs/internal/graph/model"
	"github.com/alphaleonis/nibs/internal/nib"
	"github.com/alphaleonis/nibs/internal/nibtypes"
)

// CreateNib is the resolver for the createNib field.
func (r *mutationResolver) CreateNib(ctx context.Context, input model.CreateNibInput) (*nib.Nib, error) {
	b := &nib.Nib{
		Slug:    nib.Slugify(input.Title),
		Title:   input.Title,
		Type:    "task", // default
		Version: 1,
	}

	// Optional fields with defaults documented in schema
	if input.Type != nil {
		b.Type = *input.Type
	}
	if input.Status != nil {
		b.Status = *input.Status
	}
	if input.Priority != nil {
		b.Priority = *input.Priority
	}
	if input.Estimate != nil {
		b.Estimate = *input.Estimate
	}
	if input.Body != nil {
		b.Body = *input.Body
	}
	if len(input.Tags) > 0 {
		b.Tags = input.Tags
	}
	if len(input.Documents) > 0 {
		if err := validateDocumentPaths(input.Documents); err != nil {
			return nil, err
		}
		b.Documents = input.Documents
	}

	// Handle parent (with validation)
	if input.Parent != nil && *input.Parent != "" {
		// Normalise short ID to full ID
		parentID, ok := r.Reader.NormalizeID(*input.Parent)
		if !ok {
			return nil, fmt.Errorf("parent nib not found: %s", *input.Parent)
		}
		if err := r.Validator.ValidateParent(b, parentID); err != nil {
			return nil, err
		}
		b.Parent = parentID
	}

	// Handle blocking (validate targets, will add blockedBy after creation)
	var blockingTargets []string
	if len(input.Blocking) > 0 {
		blockingTargets = make([]string, len(input.Blocking))
		for i, id := range input.Blocking {
			var ok bool
			blockingTargets[i], ok = r.Reader.NormalizeID(id)
			if !ok {
				return nil, fmt.Errorf("target nib not found: %s", id)
			}
			if _, err := r.Reader.Get(blockingTargets[i]); err != nil {
				return nil, fmt.Errorf("target nib not found: %s", id)
			}
		}
	}

	// Handle blocked_by (with cycle validation)
	if len(input.BlockedBy) > 0 {
		normalizedBlockedBy := make([]string, len(input.BlockedBy))
		for i, id := range input.BlockedBy {
			var ok bool
			normalizedBlockedBy[i], ok = r.Reader.NormalizeID(id)
			if !ok {
				return nil, fmt.Errorf("blocker nib not found: %s", id)
			}
			if _, err := r.Reader.Get(normalizedBlockedBy[i]); err != nil {
				return nil, fmt.Errorf("blocker nib not found: %s", id)
			}
		}
		// Check for cycles: same nib in both blocking and blockedBy
		for _, blockerID := range normalizedBlockedBy {
			for _, blockingID := range blockingTargets {
				if blockerID == blockingID {
					return nil, fmt.Errorf("would create cycle: new nib both blocks and is blocked by %s", blockerID)
				}
			}
		}
		b.BlockedBy = normalizedBlockedBy
	}

	// Handle positioning (afterId, beforeId, first)
	if err := r.Orderer.ApplyPositioning(b, input.AfterID, input.BeforeID, input.First); err != nil {
		return nil, err
	}

	// Handle custom prefix - pre-generate ID if prefix is provided
	if input.Prefix != nil && *input.Prefix != "" {
		idLength := 4 // default
		if cfg := r.Reader.Config(); cfg != nil && cfg.Nibs.IDLength > 0 {
			idLength = cfg.Nibs.IDLength
		}
		b.ID = nib.NewID(*input.Prefix, idLength)
	}

	if err := r.Writer.Create(b); err != nil {
		return nil, err
	}

	// Single-side: add new nib's ID to each blocking target's blockedBy
	for _, targetID := range blockingTargets {
		if target, err := r.Reader.Get(targetID); err == nil {
			targetETag := target.ETag()
			target.AddBlockedBy(b.ID)
			if err := r.Writer.Update(target, &targetETag); err != nil {
				return nil, fmt.Errorf("created nib %s but failed to set blocking on %s: %w", b.ID, targetID, err)
			}
		}
	}

	return b, nil
}

// UpdateNib is the resolver for the updateNib field.
// Clone-before-mutate: all mutations are applied to a clone of the in-memory nib.
// The original pointer is only replaced via Writer.Update on success, so any
// validation or persistence failure leaves the in-memory store untouched.
func (r *mutationResolver) UpdateNib(ctx context.Context, id string, input model.UpdateNibInput) (*nib.Nib, error) {
	original, err := r.Reader.Get(id)
	if err != nil {
		return nil, err
	}

	// Validate mutually exclusive field pairs (no mutation yet, safe before clone)
	if err := checkMutualExclusion("body and bodyMod", input.Body, input.BodyMod); err != nil {
		return nil, err
	}
	if err := checkMutualExclusion("tags and addTags/removeTags", input.Tags, input.AddTags, input.RemoveTags); err != nil {
		return nil, err
	}
	if err := checkMutualExclusion("documents and addDocuments/removeDocuments", input.Documents, input.AddDocuments, input.RemoveDocuments); err != nil {
		return nil, err
	}

	// Clone before mutating — all changes go to b, original stays pristine
	b := original.Clone()

	// Update fields if provided
	if input.Title != nil {
		b.Title = *input.Title
	}
	if input.Status != nil {
		b.Status = *input.Status
	}
	if input.Type != nil {
		b.Type = *input.Type
		// Re-validate existing parent against the new type (when parent isn't also being changed)
		if b.Parent != "" && input.Parent == nil {
			if err := r.validateAndSetParent(b, b.Parent); err != nil {
				return nil, err
			}
		}
		// Validate that existing children are still valid under the new type.
		for _, link := range r.Reader.FindIncomingLinks(b.ID) {
			if link.LinkType == "parent" {
				if err := nibtypes.ValidateParentType(link.FromNib.EffectiveType(), b.EffectiveType()); err != nil {
					return nil, fmt.Errorf("type change would invalidate child %s: %w", link.FromNib.ID, err)
				}
			}
		}
	}
	if input.Priority != nil {
		b.Priority = *input.Priority
	}
	if input.Estimate != nil {
		b.Estimate = *input.Estimate
	}
	if input.Body != nil {
		b.Body = *input.Body
	} else if input.BodyMod != nil {
		var replacements []nib.BodyReplacement
		for _, op := range input.BodyMod.Replace {
			replacements = append(replacements, nib.BodyReplacement{Old: op.Old, New: op.New})
		}
		var appendText string
		if input.BodyMod.Append != nil {
			appendText = *input.BodyMod.Append
		}
		newBody, err := nib.ApplyBodyMod(b.Body, replacements, appendText)
		if err != nil {
			return nil, err
		}
		b.Body = newBody
	}
	// Handle tags
	if input.Tags != nil {
		b.Tags = input.Tags
	} else if input.AddTags != nil || input.RemoveTags != nil {
		// Build a set of current tags
		tagSet := make(map[string]bool)
		for _, tag := range b.Tags {
			tagSet[tag] = true
		}

		// Add new tags
		if input.AddTags != nil {
			for _, tag := range input.AddTags {
				tagSet[tag] = true
			}
		}

		// Remove tags
		if input.RemoveTags != nil {
			for _, tag := range input.RemoveTags {
				delete(tagSet, tag)
			}
		}

		// Convert back to slice
		newTags := make([]string, 0, len(tagSet))
		for tag := range tagSet {
			newTags = append(newTags, tag)
		}
		b.Tags = newTags
	}

	// Handle documents (same pattern as tags)
	if input.Documents != nil {
		if err := validateDocumentPaths(input.Documents); err != nil {
			return nil, err
		}
		b.Documents = input.Documents
	} else if input.AddDocuments != nil || input.RemoveDocuments != nil {
		if err := validateDocumentPaths(input.AddDocuments); err != nil {
			return nil, err
		}
		if err := validateDocumentPaths(input.RemoveDocuments); err != nil {
			return nil, err
		}
		docSet := make(map[string]bool)
		for _, d := range b.Documents {
			docSet[d] = true
		}
		for _, d := range input.AddDocuments {
			docSet[d] = true
		}
		for _, d := range input.RemoveDocuments {
			delete(docSet, d)
		}
		newDocs := make([]string, 0, len(docSet))
		for d := range docSet {
			newDocs = append(newDocs, d)
		}
		b.Documents = newDocs
	}

	// Handle parent relationship
	if input.Parent != nil {
		if err := r.validateAndSetParent(b, *input.Parent); err != nil {
			return nil, err
		}
	}

	// Handle blocking relationships
	if input.AddBlocking != nil {
		if err := r.validateAndAddBlocking(b, input.AddBlocking); err != nil {
			return nil, err
		}
	}
	if input.RemoveBlocking != nil {
		if err := r.removeBlockingRelationships(b, input.RemoveBlocking); err != nil {
			return nil, err
		}
	}

	// Handle blocked-by relationships
	if input.AddBlockedBy != nil {
		if err := r.validateAndAddBlockedBy(b, input.AddBlockedBy); err != nil {
			return nil, err
		}
	}
	if input.RemoveBlockedBy != nil {
		r.removeBlockedByRelationships(b, input.RemoveBlockedBy)
	}

	// ETag validation now happens inside Update() under write lock.
	// Writer.Update replaces the in-memory pointer with b (the clone).
	if err := r.Writer.Update(b, input.IfMatch); err != nil {
		return nil, err
	}

	// Auto-activation: when a child is set to in-progress, propagate upward
	// to any parent that is still in todo or draft status.
	if input.Status != nil && *input.Status == "in-progress" && b.Parent != "" {
		cfg := r.Reader.Config()
		if cfg != nil && cfg.Nibs.AutoActivation {
			r.activateParentChain(b.ID, b.Parent)
		}
	}

	return b, nil
}

// DeleteNib is the resolver for the deleteNib field.
func (r *mutationResolver) DeleteNib(ctx context.Context, id string) (bool, error) {
	// Verify nib exists
	_, err := r.Reader.Get(id)
	if err != nil {
		return false, err
	}

	// Remove incoming links first
	if _, err := r.Writer.RemoveLinksTo(id); err != nil {
		return false, err
	}

	// Delete the nib
	if err := r.Writer.Delete(id); err != nil {
		return false, err
	}

	return true, nil
}

// ArchiveNib is the resolver for the archiveNib field.
// Unlike DeleteNib, incoming links are intentionally preserved because archived
// nibs remain accessible and may be unarchived later.
func (r *mutationResolver) ArchiveNib(ctx context.Context, id string) (bool, error) {
	// Verify nib exists
	_, err := r.Reader.Get(id)
	if err != nil {
		return false, err
	}

	// Archive the nib
	if err := r.Writer.Archive(id); err != nil {
		return false, err
	}

	return true, nil
}

// SetParent is the resolver for the setParent field.
func (r *mutationResolver) SetParent(ctx context.Context, id string, parentID *string, ifMatch *string) (*nib.Nib, error) {
	b, err := r.Reader.Get(id)
	if err != nil {
		return nil, err
	}

	newParent := ""
	if parentID != nil {
		newParent = *parentID
	}

	// validateAndSetParent handles normalization, validation, cycle detection,
	// and order key recalculation when the parent changes.
	if err := r.validateAndSetParent(b, newParent); err != nil {
		return nil, err
	}

	// ETag validation now happens inside Update() under write lock
	if err := r.Writer.Update(b, ifMatch); err != nil {
		return nil, err
	}
	return b, nil
}

// AddBlocking is the resolver for the addBlocking field.
// Single-side storage: adds id to target's blockedBy list (not to id's Blocking field).
func (r *mutationResolver) AddBlocking(ctx context.Context, id string, targetID string) (*nib.Nib, error) {
	b, err := r.Reader.Get(id)
	if err != nil {
		return nil, err
	}

	// Normalise short ID to full ID
	normalizedTargetID, ok := r.Reader.NormalizeID(targetID)
	if !ok {
		return nil, fmt.Errorf("target nib not found: %s", targetID)
	}

	if normalizedTargetID == b.ID {
		return nil, fmt.Errorf("nib cannot block itself")
	}

	// Check target exists
	target, err := r.Reader.Get(normalizedTargetID)
	if err != nil {
		return nil, fmt.Errorf("target nib not found: %s", targetID)
	}

	// Check for cycles: adding b→target means target.blockedBy += b.ID
	if cycle := r.Validator.DetectCycle(normalizedTargetID, "blocked_by", b.ID); cycle != nil {
		return nil, fmt.Errorf("would create cycle: %v", cycle)
	}

	// Single-side: add blocker ID to target's blockedBy
	// Compute ETag before modification for require_if_match compatibility
	targetETag := target.ETag()
	target.AddBlockedBy(b.ID)
	if err := r.Writer.Update(target, &targetETag); err != nil {
		return nil, err
	}
	return b, nil
}

// RemoveBlocking is the resolver for the removeBlocking field.
// Single-side storage: removes id from target's blockedBy list.
func (r *mutationResolver) RemoveBlocking(ctx context.Context, id string, targetID string) (*nib.Nib, error) {
	b, err := r.Reader.Get(id)
	if err != nil {
		return nil, err
	}

	// Normalise short ID to full ID (no-op if target doesn't exist — just return source nib)
	normalizedTargetID, _ := r.Reader.NormalizeID(targetID)
	// RemoveBlocking is a no-op for non-existent targets (acceptable behavior)

	// Single-side: remove blocker ID from target's blockedBy
	if target, err := r.Reader.Get(normalizedTargetID); err == nil {
		targetETag := target.ETag()
		if target.RemoveBlockedBy(b.ID) {
			if err := r.Writer.Update(target, &targetETag); err != nil {
				return nil, err
			}
		}
	}

	return b, nil
}

// AddBlockedBy is the resolver for the addBlockedBy field.
// Single-side storage: only modifies this nib's blockedBy field.
func (r *mutationResolver) AddBlockedBy(ctx context.Context, id string, targetID string, ifMatch *string) (*nib.Nib, error) {
	b, err := r.Reader.Get(id)
	if err != nil {
		return nil, err
	}

	// Normalise short ID to full ID
	normalizedTargetID, ok := r.Reader.NormalizeID(targetID)
	if !ok {
		return nil, fmt.Errorf("blocker nib not found: %s", targetID)
	}

	if normalizedTargetID == b.ID {
		return nil, fmt.Errorf("nib cannot be blocked by itself")
	}

	// Check target exists
	if _, err := r.Reader.Get(normalizedTargetID); err != nil {
		return nil, fmt.Errorf("blocker nib not found: %s", targetID)
	}

	// Check for cycles via blocked_by links
	if cycle := r.Validator.DetectCycle(b.ID, "blocked_by", normalizedTargetID); cycle != nil {
		return nil, fmt.Errorf("would create cycle: %v", cycle)
	}

	b.AddBlockedBy(normalizedTargetID)
	if err := r.Writer.Update(b, ifMatch); err != nil {
		return nil, err
	}
	return b, nil
}

// RemoveBlockedBy is the resolver for the removeBlockedBy field.
// Single-side storage: only modifies this nib's blockedBy field.
func (r *mutationResolver) RemoveBlockedBy(ctx context.Context, id string, targetID string, ifMatch *string) (*nib.Nib, error) {
	b, err := r.Reader.Get(id)
	if err != nil {
		return nil, err
	}

	// Normalise short ID to full ID (no-op if target doesn't exist — just remove any matching ID)
	normalizedTargetID, _ := r.Reader.NormalizeID(targetID)
	// RemoveBlockedBy is a no-op for non-existent targets (acceptable behavior)

	b.RemoveBlockedBy(normalizedTargetID)
	if err := r.Writer.Update(b, ifMatch); err != nil {
		return nil, err
	}
	return b, nil
}

// ReorderNib is the resolver for the reorderNib field.
func (r *mutationResolver) ReorderNib(ctx context.Context, id string, afterID *string, beforeID *string, first *bool, parentID *string, ifMatch *string) (*nib.Nib, error) {
	b, err := r.Reader.Get(id)
	if err != nil {
		return nil, err
	}

	hasAfter := afterID != nil && *afterID != ""
	hasBefore := beforeID != nil && *beforeID != ""
	hasFirst := first != nil && *first

	count := 0
	if hasAfter {
		count++
	}
	if hasBefore {
		count++
	}
	if hasFirst {
		count++
	}
	if count == 0 {
		return nil, fmt.Errorf("at least one positioning flag (afterId, beforeId, first) is required")
	}
	if count > 1 {
		return nil, fmt.Errorf("at most one of afterId, beforeId, first may be specified")
	}

	// Optional reparent: change parent before reordering (atomic cross-parent move)
	if parentID != nil {
		newParent := *parentID
		if err := r.validateAndSetParent(b, newParent); err != nil {
			return nil, err
		}
	}

	// Get siblings from the (possibly new) parent
	var siblings []*nib.Nib
	if b.Parent == "" {
		siblings = r.Orderer.getRootSiblings()
	} else {
		siblings = r.Orderer.GetSortedSiblings(b.Parent)
	}

	// Remove self from siblings list to avoid self-referencing
	var filtered []*nib.Nib
	for _, s := range siblings {
		if s.ID != b.ID {
			filtered = append(filtered, s)
		}
	}

	if hasAfter {
		if err := r.Orderer.positionAfter(b, *afterID, filtered); err != nil {
			return nil, err
		}
	} else if hasBefore {
		if err := r.Orderer.positionBefore(b, *beforeID, filtered); err != nil {
			return nil, err
		}
	} else if hasFirst {
		if len(filtered) == 0 {
			b.Order = nib.OrderInitial()
		} else {
			b.Order = nib.OrderFirst(filtered[0].Order)
		}
	}

	if err := r.Writer.Update(b, ifMatch); err != nil {
		return nil, err
	}
	return b, nil
}

// ReorderChildren is the resolver for the reorderChildren field.
func (r *mutationResolver) ReorderChildren(ctx context.Context, parentID string, childIds []string, ifMatch []*model.ChildEtag) ([]*nib.Nib, error) {
	return r.reorderChildrenImpl(parentID, childIds, ifMatch)
}

// ReorderSiblings is the resolver for the reorderSiblings field.
func (r *mutationResolver) ReorderSiblings(ctx context.Context, siblingIds []string, afterID *string, beforeID *string, first *bool, ifMatch []*model.ChildEtag) ([]*nib.Nib, error) {
	return r.reorderSiblingsImpl(siblingIds, afterID, beforeID, first, ifMatch)
}

// Type is the resolver for the type field. The stored Nib keeps Type empty when
// the file omits it (so the etag witnesses the on-disk bytes); this resolver
// applies the presentation default so the non-nullable field always resolves a
// value ("task"). See nib.DefaultType and nibs-7d3o.
func (r *nibResolver) Type(ctx context.Context, obj *nib.Nib) (string, error) {
	return obj.EffectiveType(), nil
}

// Priority is the resolver for the priority field. Mirrors Type: the stored Nib
// keeps Priority empty when the file omits it; this resolver applies the "normal"
// presentation default for the non-nullable field. See nib.DefaultPriority.
func (r *nibResolver) Priority(ctx context.Context, obj *nib.Nib) (string, error) {
	return obj.EffectivePriority(), nil
}

// ParentID is the resolver for the parentId field.
func (r *nibResolver) ParentID(ctx context.Context, obj *nib.Nib) (*string, error) {
	if obj.Parent == "" {
		return nil, nil
	}
	return &obj.Parent, nil
}

// BlockingIds is the resolver for the blockingIds field.
// Computed: scans for active nibs that have this nib in their blockedBy list.
// A resolved nib is not considered to be blocking anything.
func (r *nibResolver) BlockingIds(ctx context.Context, obj *nib.Nib) ([]string, error) {
	if isResolvedStatus(obj.Status) {
		return []string{}, nil
	}
	incoming := r.Reader.FindIncomingLinks(obj.ID)
	var ids []string
	for _, link := range incoming {
		if link.LinkType == "blocked_by" && !isResolvedStatus(link.FromNib.Status) {
			ids = append(ids, link.FromNib.ID)
		}
	}
	if ids == nil {
		ids = []string{}
	}
	return ids, nil
}

// BlockedByIds is the resolver for the blockedByIds field.
// Returns only IDs of active (non-completed, non-scrapped) blockers.
func (r *nibResolver) BlockedByIds(ctx context.Context, obj *nib.Nib) ([]string, error) {
	var ids []string
	for _, blockerID := range obj.BlockedBy {
		if blocker, err := r.Reader.Get(blockerID); err == nil {
			if !isResolvedStatus(blocker.Status) {
				ids = append(ids, blockerID)
			}
		}
	}
	if ids == nil {
		ids = []string{}
	}
	return ids, nil
}

// BlockedBy is the resolver for the blockedBy field.
// Returns only active (non-completed, non-scrapped) blockers.
func (r *nibResolver) BlockedBy(ctx context.Context, obj *nib.Nib, filter *model.NibFilter) ([]*nib.Nib, error) {
	var result []*nib.Nib
	for _, blockerID := range obj.BlockedBy {
		if blocker, err := r.Reader.Get(blockerID); err == nil {
			if !isResolvedStatus(blocker.Status) {
				result = append(result, blocker)
			}
		}
	}

	return ApplyFilter(ctx, result, filter, r.Reader, r.Resolver.Blocking), nil
}

// Blocking is the resolver for the blocking field.
// Computed: returns active nibs whose BlockedBy field contains this nib's ID.
// A resolved nib is not considered to be blocking anything.
func (r *nibResolver) Blocking(ctx context.Context, obj *nib.Nib, filter *model.NibFilter) ([]*nib.Nib, error) {
	if isResolvedStatus(obj.Status) {
		return ApplyFilter(ctx, nil, filter, r.Reader, r.Resolver.Blocking), nil
	}
	incoming := r.Reader.FindIncomingLinks(obj.ID)
	var result []*nib.Nib
	for _, link := range incoming {
		if link.LinkType == "blocked_by" && !isResolvedStatus(link.FromNib.Status) {
			result = append(result, link.FromNib)
		}
	}

	return ApplyFilter(ctx, result, filter, r.Reader, r.Resolver.Blocking), nil
}

// Parent is the resolver for the parent field.
func (r *nibResolver) Parent(ctx context.Context, obj *nib.Nib) (*nib.Nib, error) {
	if obj.Parent == "" {
		return nil, nil
	}
	// Filter out broken links
	parent, err := r.Reader.Get(obj.Parent)
	if errors.Is(err, nib.ErrNotFound) {
		return nil, nil
	}
	return parent, err
}

// Children is the resolver for the children field.
func (r *nibResolver) Children(ctx context.Context, obj *nib.Nib, filter *model.NibFilter, sort *model.NibSort) ([]*nib.Nib, error) {
	result := r.Orderer.GetSortedSiblings(obj.ID)
	result = ApplyFilter(ctx, result, filter, r.Reader, r.Resolver.Blocking)
	ApplySorting(result, sort, r.Reader.Config())
	return result, nil
}

// MentionIds is the resolver for the mentionIds field.
// Returns the IDs of nibs mentioned via `#<id>` in this nib's body.
//
// Unlike BlockedBy/Blocking, mentions are informational and include nibs in
// all statuses (archived, scrapped, completed). Callers who want active-only
// should request the `mentions` field with a filter instead, e.g.
// `mentions(filter: { excludeStatus: ["completed", "scrapped"] }) { id }`.
func (r *nibResolver) MentionIds(ctx context.Context, obj *nib.Nib) ([]string, error) {
	return MentionIDList(cachedMentions(ctx, r.Reader, obj.ID)), nil
}

// MentionedByIds is the resolver for the mentionedByIds field.
// Returns the IDs of nibs whose bodies mention this nib via `#<id>`.
//
// Unlike BlockedBy/Blocking, mentions are informational and include nibs in
// all statuses (archived, scrapped, completed). Callers who want active-only
// should request the `mentionedBy` field with a filter, e.g.
// `mentionedBy(filter: { excludeStatus: ["completed", "scrapped"] }) { id }`.
func (r *nibResolver) MentionedByIds(ctx context.Context, obj *nib.Nib) ([]string, error) {
	return MentionIDList(cachedMentionedBy(ctx, r.Reader, obj.ID)), nil
}

// Mentions is the resolver for the mentions field.
//
// Unlike BlockedBy/Blocking, mentions are informational and include nibs in
// all statuses (archived, scrapped, completed). Callers who want active-only
// should pass `filter: { excludeStatus: ["completed", "scrapped"] }`.
func (r *nibResolver) Mentions(ctx context.Context, obj *nib.Nib, filter *model.NibFilter) ([]*nib.Nib, error) {
	result := cachedMentions(ctx, r.Reader, obj.ID)
	return ApplyFilter(ctx, result, filter, r.Reader, r.Resolver.Blocking), nil
}

// MentionedBy is the resolver for the mentionedBy field.
//
// Unlike BlockedBy/Blocking, mentions are informational and include nibs in
// all statuses (archived, scrapped, completed). Callers who want active-only
// should pass `filter: { excludeStatus: ["completed", "scrapped"] }`.
func (r *nibResolver) MentionedBy(ctx context.Context, obj *nib.Nib, filter *model.NibFilter) ([]*nib.Nib, error) {
	result := cachedMentionedBy(ctx, r.Reader, obj.ID)
	return ApplyFilter(ctx, result, filter, r.Reader, r.Resolver.Blocking), nil
}

// Nib is the resolver for the nib field.
func (r *queryResolver) Nib(ctx context.Context, id string) (*nib.Nib, error) {
	b, err := r.Reader.Get(id)
	if errors.Is(err, nib.ErrNotFound) {
		return nil, nil
	}
	return b, err
}

// Nibs is the resolver for the nibs field.
func (r *queryResolver) Nibs(ctx context.Context, filter *model.NibFilter, sort *model.NibSort) ([]*nib.Nib, error) {
	var nibs []*nib.Nib

	// If search filter is provided, start with search results
	if filter != nil && filter.Search != nil && *filter.Search != "" {
		searchResults, err := r.Reader.Search(*filter.Search)
		if err != nil {
			return nil, err
		}
		nibs = searchResults
	} else {
		nibs = r.Reader.All()
	}

	result := ApplyFilter(ctx, nibs, filter, r.Reader, r.Blocking)

	// When search is active, include ancestors of matched nibs so the
	// client can build complete tree hierarchies even when only leaf
	// nodes match the search query.
	if filter != nil && filter.Search != nil && *filter.Search != "" {
		result = includeAncestors(result, r.Reader)
	}

	ApplySorting(result, sort, r.Reader.Config())
	return result, nil
}

// Config is the resolver for the config field.
func (r *queryResolver) Config(ctx context.Context) (*model.Config, error) {
	cfg := r.Reader.Config()
	return &model.Config{
		ProjectName: cfg.GetProjectName(),
		Prefix:      cfg.Nibs.Prefix,
	}, nil
}

// NibChanged is the resolver for the nibChanged field.
func (r *subscriptionResolver) NibChanged(ctx context.Context, id *string) (<-chan *model.NibChangeEvent, error) {
	eventCh, unsub := r.Subscriber.Subscribe()
	out := make(chan *model.NibChangeEvent)

	go func() {
		defer unsub()
		defer close(out)
		for {
			select {
			case <-ctx.Done():
				return
			case batch, ok := <-eventCh:
				if !ok {
					return
				}
				for _, evt := range batch {
					if id != nil && evt.NibID != *id {
						continue
					}
					event := &model.NibChangeEvent{
						Type:  evt.Type.String(),
						NibID: evt.NibID,
						Nib:   evt.Nib,
					}
					select {
					case out <- event:
					case <-ctx.Done():
						return
					}
				}
			}
		}
	}()

	return out, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Nib returns NibResolver implementation.
func (r *Resolver) Nib() NibResolver { return &nibResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type nibResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
