package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"

	"github.com/alphaleonis/nibs/internal/graph/model"
	"github.com/alphaleonis/nibs/internal/nib"
	"github.com/alphaleonis/nibs/internal/nibtypes"
	"github.com/alphaleonis/nibs/internal/updatecheck"
)

// CreateNib is the resolver for the createNib field.
func (r *mutationResolver) CreateNib(ctx context.Context, input model.CreateNibInput) (*nib.Nib, error) {
	b := &nib.Nib{
		Slug:    nib.Slugify(input.Title),
		Title:   input.Title,
		Type:    "task", // default
		Version: nib.CurrentVersion,
	}

	if input.Type != nil {
		b.Type = *input.Type
	}
	if input.Status != nil {
		b.Status = *input.Status
	}
	if input.Priority != nil {
		b.Priority = *input.Priority
	}
	if input.Estimate != nil {
		b.Estimate = *input.Estimate
	}
	if input.Body != nil {
		b.Body = *input.Body
	}
	if len(input.Tags) > 0 {
		b.Tags = input.Tags
	}
	// Area names no nib, so there is nothing to resolve here; Core.Create judges
	// it against the declared vocabulary.
	if input.Area != nil {
		b.Area = *input.Area
	}
	if len(input.Documents) > 0 {
		if err := validateDocumentPaths(input.Documents); err != nil {
			return nil, err
		}
		b.Documents = input.Documents
	}

	if input.Parent != nil && *input.Parent != "" {
		parentID, ok := r.Reader.NormalizeID(*input.Parent)
		if !ok {
			return nil, fmt.Errorf("parent nib not found: %s", *input.Parent)
		}
		if err := r.Validator.ValidateParent(b, parentID); err != nil {
			return nil, err
		}
		b.Parent = parentID
	}

	var blockingTargets []string
	if len(input.Blocking) > 0 {
		blockingTargets = make([]string, len(input.Blocking))
		for i, id := range input.Blocking {
			var ok bool
			blockingTargets[i], ok = r.Reader.NormalizeID(id)
			if !ok {
				return nil, fmt.Errorf("target nib not found: %s", id)
			}
			if _, err := r.Reader.Get(blockingTargets[i]); err != nil {
				return nil, fmt.Errorf("target nib not found: %s", id)
			}
		}
	}

	if len(input.BlockedBy) > 0 {
		normalizedBlockedBy := make([]string, len(input.BlockedBy))
		for i, id := range input.BlockedBy {
			var ok bool
			normalizedBlockedBy[i], ok = r.Reader.NormalizeID(id)
			if !ok {
				return nil, fmt.Errorf("blocker nib not found: %s", id)
			}
			if _, err := r.Reader.Get(normalizedBlockedBy[i]); err != nil {
				return nil, fmt.Errorf("blocker nib not found: %s", id)
			}
		}
		for _, blockerID := range normalizedBlockedBy {
			for _, blockingID := range blockingTargets {
				if blockerID == blockingID {
					return nil, fmt.Errorf("would create cycle: new nib both blocks and is blocked by %s", blockerID)
				}
			}
		}
		b.BlockedBy = normalizedBlockedBy
	}

	placement, err := PlacementFromArgs(input.AfterID, input.BeforeID, input.First)
	if err != nil {
		return nil, err
	}
	if err := r.Orderer.Place(ScopeParent, b, placement); err != nil {
		return nil, err
	}

	// A custom prefix means generating the id here, redrawing on a collision as
	// Core.Create does for its own draws. A draw that races a concurrent write
	// between this check and the store lock is caught by Create's duplicate
	// refusal.
	if input.Prefix != nil && *input.Prefix != "" {
		idLength := 4 // default
		if cfg := r.Reader.Config(); cfg != nil && cfg.Nibs.IDLength > 0 {
			idLength = cfg.Nibs.IDLength
		}
		for range 100 {
			id := newPrefixedNibID(*input.Prefix, idLength)
			// Reader.Get prefix-prepends on a miss, so a draw can read as taken
			// by a DIFFERENT nib under the store prefix. A false "free" is
			// impossible — the exact match is tried first.
			if _, err := r.Reader.Get(id); err != nil {
				b.ID = id
				break
			}
		}
		if b.ID == "" {
			return nil, fmt.Errorf("could not generate a free nib id with prefix %q in 100 draws — the id space (length %d) is exhausted or the generator is broken; raise nibs.id_length", *input.Prefix, idLength)
		}
	}

	if err := r.Writer.Create(b); err != nil {
		return nil, err
	}

	// Single-side: the new nib's ID goes into each target's blockedBy. Guard
	// existence first so a target that vanished stays a no-op rather than
	// surfacing GetForUpdate's not-found error.
	for _, targetID := range blockingTargets {
		if _, err := r.Reader.Get(targetID); err == nil {
			if err := r.updateTargetClone(targetID, func(c *nib.Nib) bool {
				c.AddBlockedBy(b.ID)
				return true
			}); err != nil {
				return nil, fmt.Errorf("created nib %s but failed to set blocking on %s: %w", b.ID, targetID, err)
			}
		}
	}

	// Writer.Create installed b AS the shared store entry — return a snapshot,
	// never b itself.
	return r.snapshotResult(b.ID)
}

// UpdateNib is the resolver for the updateNib field.
func (r *mutationResolver) UpdateNib(ctx context.Context, id string, input model.UpdateNibInput) (*nib.Nib, error) {
	// GetForUpdate returns an owned clone; mutate b freely — the shared store nib
	// stays pristine until Writer.Update installs b.
	b, err := r.Reader.GetForUpdate(id)
	if err != nil {
		return nil, err
	}

	if err := checkMutualExclusion("body and bodyMod", input.Body, input.BodyMod); err != nil {
		return nil, err
	}
	if err := checkMutualExclusion("tags and addTags/removeTags", input.Tags, input.AddTags, input.RemoveTags); err != nil {
		return nil, err
	}
	if err := checkMutualExclusion("documents and addDocuments/removeDocuments", input.Documents, input.AddDocuments, input.RemoveDocuments); err != nil {
		return nil, err
	}

	// All four enum fields land in this block, ABOVE the type-change branch that
	// follows, so preValidateSubject between them sees the final subject and still
	// precedes every step that writes to another nib's file.
	if input.Title != nil {
		b.Title = *input.Title
	}
	// A RAW comparison, where the effective-type check below needs
	// EffectiveType(): status has no normalizing accessor, so a form echoes back
	// the same "" it read and no no-op can disguise itself as a change.
	statusChanged := input.Status != nil && *input.Status != b.Status
	if input.Status != nil {
		b.Status = *input.Status
	}
	oldEffectiveType := b.EffectiveType()
	if input.Type != nil {
		b.Type = *input.Type
	}
	// priority/estimate are graphql.Omittable[*string]: an explicit JSON `null`
	// clears the field, an omitted field leaves it unchanged. See gqlgen.yml.
	if p, ok := input.Priority.ValueOK(); ok {
		if p != nil {
			b.Priority = *p
		} else {
			b.Priority = ""
		}
	}
	if e, ok := input.Estimate.ValueOK(); ok {
		if e != nil {
			b.Estimate = *e
		} else {
			b.Estimate = ""
		}
	}

	// The milestone reads three ways on the wire — omitted leaves it, null or ""
	// clears it, an id assigns. A CLEAR's FIELD effect is applied here, above
	// the axis check, so preValidateSubject judges the state this request leaves
	// rather than the stale pre-write assignment: one call carrying both a type
	// change to milestone and a clear ends valid. Its key drop stays in the
	// milestone block below. An ASSIGNMENT is not pre-applied at all — it is
	// judged by validateAndSetMilestone against the chain the nib will sit on,
	// which the parent block has not yet settled here.
	milestoneSet, newMilestone := false, ""
	if m, ok := input.Milestone.ValueOK(); ok {
		milestoneSet = true
		if m != nil {
			newMilestone = *m
		}
	}
	if milestoneSet && newMilestone == "" {
		b.Milestone = ""
	}

	// The writes that can put a NEW pair into a milestone queue (decision 2.3):
	// an assignment, where the subject enters a queue, and a new dependency edge
	// in either spelling, which gives a pair already sharing a queue its blocking
	// half. A clear and the remove-forms only take pairs away. Taken here: it
	// must read the store before Writer.Update lands, and nothing above writes.
	var lintBefore map[inversionKey]bool
	if (milestoneSet && newMilestone != "") || len(input.AddBlocking) > 0 || len(input.AddBlockedBy) > 0 {
		lintBefore = r.beginQueueLint(ctx, b.ID)
	}

	// The area axis reads the same three ways, and BOTH directions are applied
	// here: an area names no nib, moves no queue and touches no other file.
	// Applying it above the guards is what makes repair possible — a nib whose
	// file carries an undeclared area is refused by every write, so the request
	// that clears or replaces the value is judged on the state it LEAVES.
	if a, ok := input.Area.ValueOK(); ok {
		b.Area = ""
		if a != nil {
			b.Area = *a
		}
	}

	// Everything above assigns to b, the owned clone, and reads nothing off disk.
	// Every step BELOW can reach a write to another nib's file, so the subject's
	// write-free guards run here — a doomed update must not leave a durable edit
	// on a nib it then reports as failed. The blocking handlers persist each
	// target directly; a real parent change (the type-change branch below and the
	// parent block further down) and a milestone ASSIGNMENT each recalculate the
	// order key, which reads its group through Orderer.backfillKeys — a lazy
	// read-path repair that PERSISTS a key to any member that has none.
	if err := r.preValidateSubject(b, input.IfMatch); err != nil {
		return nil, err
	}

	// Decision 1.5 at the model boundary. It cannot move into preValidateSubject:
	// `nibs close` calls PreValidateSubject BEFORE its dispositions drain the
	// queue (closePreValidateSubject), so a guard there would refuse the very
	// escapes that exist to answer this refusal.
	//
	// Gated on the status actually CHANGING, not merely being supplied. The web
	// edit form sends `status` on every save, so a title-only edit arrives
	// carrying the value the nib already holds, and refusing that would make a
	// milestone already sitting on a releasing status over a live queue
	// uneditable from the web. `nibs check` reports that standing offense
	// (nibcore's ClosedMilestoneQueue finding). Revising one releasing reason to
	// another IS a close and is still refused.
	if statusChanged {
		if err := r.refuseClosingFullQueue(ctx, b); err != nil {
			return nil, err
		}
	}

	if input.Type != nil {
		// Only re-validate relationships when the EFFECTIVE type ACTUALLY changed.
		// The web edit form always sends `type`, so a title-only edit arrives with
		// type present but equal. No-op detection must use EffectiveType(): a
		// type-less nib carries "" on disk while the Nib.type field reads back
		// "task", and a raw comparison would call that echo a change and
		// re-validate an untouched (possibly already invalid) parent/child
		// relationship, dead-ending every edit of such a nib.
		if b.EffectiveType() != oldEffectiveType {
			// Decision 1.5's TYPE-FLIP door. A milestone holding assignments
			// cannot stop being one: every nib pointing at it would keep a
			// `milestone:` naming a non-milestone, which confers no membership and
			// is what `nibs check` reports as an invalid target. It also closes
			// the retype-away / close / retype-back route into the state the close
			// guard refuses.
			//
			// The queue is read here, while the STORED type is still milestone, so
			// View.DirectMembers answers on the assignment axis. Openness is not
			// consulted: a closed member's assignment is still a live link this
			// change would invalidate.
			if oldEffectiveType == "milestone" {
				if held := cachedMembershipView(ctx, r.Reader).DirectMembers(b.ID); len(held) > 0 {
					return nil, &MilestoneRetypeError{
						MilestoneID: b.ID,
						NewType:     b.EffectiveType(),
						Held:        memberIDs(held),
					}
				}
			}

			// Re-validate the existing parent against the new type, when the parent
			// field was omitted. "Existing parent" is the RESOLVED link, not the
			// stored string (see resolvedParent): a link naming no nib names no
			// parent, and testing the stored string instead aborts the whole
			// mutation with "parent nib not found" over a field the caller never
			// touched.
			if parentID := resolvedParentID(b, r.Reader); parentID != "" && !input.Parent.IsSet() {
				if err := r.validateAndSetParent(b, parentID); err != nil {
					return nil, err
				}
			}
			for _, link := range r.Reader.FindIncomingLinks(b.ID) {
				if link.LinkType == "parent" {
					if err := nibtypes.ValidateParentType(link.FromNib.EffectiveType(), b.EffectiveType()); err != nil {
						return nil, fmt.Errorf("type change would invalidate child %s: %w", link.FromNib.ID, err)
					}
				}
			}
		}
	}
	if input.Body != nil {
		b.Body = *input.Body
	} else if input.BodyMod != nil {
		var replacements []nib.BodyReplacement
		for _, op := range input.BodyMod.Replace {
			replacements = append(replacements, nib.BodyReplacement{Old: op.Old, New: op.New})
		}
		var appendText string
		if input.BodyMod.Append != nil {
			appendText = *input.BodyMod.Append
		}
		newBody, err := nib.ApplyBodyMod(b.Body, replacements, appendText)
		if err != nil {
			return nil, err
		}
		b.Body = newBody
	}
	if input.Tags != nil {
		b.Tags = input.Tags
	} else if input.AddTags != nil || input.RemoveTags != nil {
		tagSet := make(map[string]bool)
		for _, tag := range b.Tags {
			tagSet[tag] = true
		}

		if input.AddTags != nil {
			for _, tag := range input.AddTags {
				tagSet[tag] = true
			}
		}

		if input.RemoveTags != nil {
			for _, tag := range input.RemoveTags {
				delete(tagSet, tag)
			}
		}

		newTags := make([]string, 0, len(tagSet))
		for tag := range tagSet {
			newTags = append(newTags, tag)
		}
		b.Tags = newTags
	}

	if input.Documents != nil {
		if err := validateDocumentPaths(input.Documents); err != nil {
			return nil, err
		}
		b.Documents = input.Documents
	} else if input.AddDocuments != nil || input.RemoveDocuments != nil {
		if err := validateDocumentPaths(input.AddDocuments); err != nil {
			return nil, err
		}
		if err := validateDocumentPaths(input.RemoveDocuments); err != nil {
			return nil, err
		}
		docSet := make(map[string]bool)
		for _, d := range b.Documents {
			docSet[d] = true
		}
		for _, d := range input.AddDocuments {
			docSet[d] = true
		}
		for _, d := range input.RemoveDocuments {
			delete(docSet, d)
		}
		newDocs := make([]string, 0, len(docSet))
		for d := range docSet {
			newDocs = append(newDocs, d)
		}
		b.Documents = newDocs
	}

	// A request carrying BOTH a parent and a milestone change is judged on the
	// state it leaves, and each exclusivity check reads the other axis off the
	// clone. So a CLEAR runs BEFORE the parent block, which then judges the move
	// against a nib carrying no assignment rather than refusing it for one this
	// request drops; an ASSIGNMENT runs AFTER it, judged against the chain the
	// nib will actually sit on. Both stay before the blocking handlers.
	if milestoneSet && newMilestone == "" {
		if err := r.validateAndSetMilestone(b, ""); err != nil {
			return nil, err
		}
	}

	// parent is graphql.Omittable[*string], so the wire distinguishes three
	// cases: omitted leaves it unchanged (the type-change path above re-validates
	// it when needed), null or "" clears it to root, a non-empty id is
	// normalized, validated and set.
	if p, ok := input.Parent.ValueOK(); ok {
		newParent := ""
		if p != nil {
			newParent = *p
		}
		if err := r.validateAndSetParent(b, newParent); err != nil {
			return nil, err
		}
	}

	if milestoneSet && newMilestone != "" {
		if err := r.validateAndSetMilestone(b, newMilestone); err != nil {
			return nil, err
		}
	}

	if input.AddBlocking != nil {
		if err := r.validateAndAddBlocking(b, input.AddBlocking); err != nil {
			return nil, err
		}
	}
	if input.RemoveBlocking != nil {
		if err := r.removeBlockingRelationships(b, input.RemoveBlocking); err != nil {
			return nil, err
		}
	}

	if input.AddBlockedBy != nil {
		if err := r.validateAndAddBlockedBy(b, input.AddBlockedBy); err != nil {
			return nil, err
		}
	}
	if input.RemoveBlockedBy != nil {
		r.removeBlockedByRelationships(b, input.RemoveBlockedBy)
	}

	if err := r.Writer.Update(b, input.IfMatch); err != nil {
		return nil, err
	}

	if input.Status != nil && *input.Status == "in-progress" && b.Parent != "" {
		cfg := r.Reader.Config()
		if cfg != nil && cfg.Nibs.AutoActivation {
			r.activateParentChain(b.ID, b.Parent)
		}
	}

	// After every effect has landed, auto-activation included, so the pairs name
	// the store the caller is about to see.
	r.endQueueLint(ctx, b.ID, lintBefore)

	// Writer.Update installed b AS the shared store entry — return a snapshot.
	return r.snapshotResult(b.ID)
}

// DeleteNib is the resolver for the deleteNib field.
//
// Both halves run on the RESOLVED id. Only the immutable ID is read off the live
// pointer Get returns (see NibReader.GetSnapshot in interfaces.go).
//
// Order is load-bearing. Unlinking runs FIRST, while the target is still in the
// store, so RemoveLinksTo resolves against the same key set the stored links do.
// Afterwards it would not: with a bare-token id gone, its prefixed twin answers
// to that token, so the links this delete should have CLEARED would instead be
// re-pointed onto the twin by Core.Delete's canonicalization sweep, and the
// twin's own incoming links stripped in their place.
func (r *mutationResolver) DeleteNib(ctx context.Context, id string) (bool, error) {
	target, err := r.Reader.Get(id)
	if err != nil {
		return false, err
	}
	resolvedID := target.ID

	if _, err := r.Writer.RemoveLinksTo(resolvedID); err != nil {
		return false, err
	}

	if err := r.Writer.Delete(resolvedID); err != nil {
		return false, err
	}

	return true, nil
}

// ArchiveNib is the resolver for the archiveNib field.
// Incoming links are preserved, unlike DeleteNib: an archived nib stays in the
// store and may be unarchived.
func (r *mutationResolver) ArchiveNib(ctx context.Context, id string) (bool, error) {
	_, err := r.Reader.Get(id)
	if err != nil {
		return false, err
	}

	if err := r.Writer.Archive(id); err != nil {
		return false, err
	}

	return true, nil
}

// SetParent is the resolver for the setParent field.
func (r *mutationResolver) SetParent(ctx context.Context, id string, parentID *string, ifMatch *string) (*nib.Nib, error) {
	b, err := r.Reader.GetForUpdate(id)
	if err != nil {
		return nil, err
	}

	newParent := ""
	if parentID != nil {
		newParent = *parentID
	}

	if err := r.validateAndSetParent(b, newParent); err != nil {
		return nil, err
	}

	if err := r.Writer.Update(b, ifMatch); err != nil {
		return nil, err
	}
	// Writer.Update installed b AS the shared store entry — return a snapshot.
	return r.snapshotResult(b.ID)
}

// AddBlocking is the resolver for the addBlocking field.
// Single-side storage: adds id to target's blockedBy list (not to id's Blocking field).
func (r *mutationResolver) AddBlocking(ctx context.Context, id string, targetID string) (*nib.Nib, error) {
	b, err := r.Reader.Get(id)
	if err != nil {
		return nil, err
	}

	normalizedTargetID, ok := r.Reader.NormalizeID(targetID)
	if !ok {
		return nil, fmt.Errorf("target nib not found: %s", targetID)
	}

	if normalizedTargetID == b.ID {
		return nil, fmt.Errorf("nib cannot block itself")
	}

	if _, err := r.Reader.Get(normalizedTargetID); err != nil {
		return nil, fmt.Errorf("target nib not found: %s", targetID)
	}

	// The edge added is target.blockedBy += b.ID, hence the argument order.
	if cycle := r.Validator.DetectCycle(normalizedTargetID, "blocked_by", b.ID); cycle != nil {
		return nil, fmt.Errorf("would create cycle: %v", cycle)
	}

	// This edge can give a pair already sharing a queue its blocking half. Linted
	// on the SUBJECT, which the new pair names as the blocker.
	lintBefore := r.beginQueueLint(ctx, b.ID)

	if err := r.updateTargetClone(normalizedTargetID, func(c *nib.Nib) bool {
		c.AddBlockedBy(b.ID)
		return true
	}); err != nil {
		return nil, err
	}
	r.endQueueLint(ctx, b.ID, lintBefore)
	// b is the live Reader.Get pointer — return a snapshot, never b itself.
	return r.snapshotResult(b.ID)
}

// RemoveBlocking is the resolver for the removeBlocking field.
// Single-side storage: removes id from target's blockedBy list.
func (r *mutationResolver) RemoveBlocking(ctx context.Context, id string, targetID string) (*nib.Nib, error) {
	b, err := r.Reader.Get(id)
	if err != nil {
		return nil, err
	}

	// NormalizeID echoes the id back for a target that does not exist; the
	// existence guard below then makes the whole call a no-op.
	normalizedTargetID, _ := r.Reader.NormalizeID(targetID)

	if _, err := r.Reader.Get(normalizedTargetID); err == nil {
		if err := r.updateTargetClone(normalizedTargetID, func(c *nib.Nib) bool {
			return c.RemoveBlockedBy(b.ID)
		}); err != nil {
			return nil, err
		}
	}

	// b is the live Reader.Get pointer — return a snapshot, never b itself.
	return r.snapshotResult(b.ID)
}

// AddBlockedBy is the resolver for the addBlockedBy field.
// Single-side storage: only modifies this nib's blockedBy field.
func (r *mutationResolver) AddBlockedBy(ctx context.Context, id string, targetID string, ifMatch *string) (*nib.Nib, error) {
	b, err := r.Reader.GetForUpdate(id)
	if err != nil {
		return nil, err
	}

	normalizedTargetID, ok := r.Reader.NormalizeID(targetID)
	if !ok {
		return nil, fmt.Errorf("blocker nib not found: %s", targetID)
	}

	if normalizedTargetID == b.ID {
		return nil, fmt.Errorf("nib cannot be blocked by itself")
	}

	if _, err := r.Reader.Get(normalizedTargetID); err != nil {
		return nil, fmt.Errorf("blocker nib not found: %s", targetID)
	}

	if cycle := r.Validator.DetectCycle(b.ID, "blocked_by", normalizedTargetID); cycle != nil {
		return nil, fmt.Errorf("would create cycle: %v", cycle)
	}

	lintBefore := r.beginQueueLint(ctx, b.ID)

	b.AddBlockedBy(normalizedTargetID)
	if err := r.Writer.Update(b, ifMatch); err != nil {
		return nil, err
	}
	r.endQueueLint(ctx, b.ID, lintBefore)

	// Writer.Update installed b AS the shared store entry — return a snapshot.
	return r.snapshotResult(b.ID)
}

// RemoveBlockedBy is the resolver for the removeBlockedBy field.
// Single-side storage: only modifies this nib's blockedBy field.
func (r *mutationResolver) RemoveBlockedBy(ctx context.Context, id string, targetID string, ifMatch *string) (*nib.Nib, error) {
	b, err := r.Reader.GetForUpdate(id)
	if err != nil {
		return nil, err
	}

	// NormalizeID echoes the id back for a target that does not exist, so the
	// removal below simply matches nothing.
	normalizedTargetID, _ := r.Reader.NormalizeID(targetID)

	b.RemoveBlockedBy(normalizedTargetID)
	if err := r.Writer.Update(b, ifMatch); err != nil {
		return nil, err
	}
	// Writer.Update installed b AS the shared store entry — return a snapshot.
	return r.snapshotResult(b.ID)
}

// ReorderNib is the resolver for the reorderNib field.
func (r *mutationResolver) ReorderNib(ctx context.Context, id string, afterID *string, beforeID *string, first *bool, parentID *string, ifMatch *string, scope model.OrderScope) (*nib.Nib, error) {
	b, err := r.Reader.GetForUpdate(id)
	if err != nil {
		return nil, err
	}

	pos, err := PositionFromArgs(afterID, beforeID, first)
	if err != nil {
		return nil, err
	}

	// Only a queue move can create an inversion: a sibling reorder changes no
	// position inside a milestone's queue.
	var lintBefore map[inversionKey]bool
	if scope == model.OrderScopeMilestone {
		lintBefore = r.beginQueueLint(ctx, b.ID)
	}

	// Optional reparent, applied before the move (an atomic cross-parent move).
	// ContainerChange carries the wire reading — note the contrast with
	// updateNib's omittable parent, where null is the clear.
	if target, ok := ContainerChangeFromArg(parentID).Requested(); ok {
		if scope == model.OrderScopeMilestone {
			return nil, fmt.Errorf("parentId reparents within the parent scope; a milestone-queue reorder takes no container change (reassign the nib with updateNib's milestone field instead)")
		}
		if err := r.validateAndSetParent(b, target); err != nil {
			return nil, err
		}
	}

	// Move resolves b's (possibly new) group in the requested scope itself, so an
	// anchor must be found in the set siblingId and `nibs rel --rel siblings`
	// report for b in the parent scope, or the milestone filter's queue in the
	// milestone scope.
	if err := r.Orderer.Move(scopeFromModel(scope), b, pos); err != nil {
		return nil, err
	}

	if err := r.Writer.Update(b, ifMatch); err != nil {
		return nil, err
	}
	r.endQueueLint(ctx, b.ID, lintBefore)

	// Writer.Update installed b AS the shared store entry — return a snapshot.
	return r.snapshotResult(b.ID)
}

// ReorderChildren is the resolver for the reorderChildren field.
func (r *mutationResolver) ReorderChildren(ctx context.Context, parentID string, childIds []string, ifMatch []*model.ChildEtag) ([]*nib.Nib, error) {
	return r.reorderChildrenImpl(parentID, childIds, ifMatch)
}

// ReorderSiblings is the resolver for the reorderSiblings field.
func (r *mutationResolver) ReorderSiblings(ctx context.Context, siblingIds []string, afterID *string, beforeID *string, first *bool, ifMatch []*model.ChildEtag) ([]*nib.Nib, error) {
	return r.reorderSiblingsImpl(siblingIds, afterID, beforeID, first, ifMatch)
}

// RenameArea is the resolver for the renameArea field.
func (r *mutationResolver) RenameArea(ctx context.Context, input model.RenameAreaInput) (*model.Config, error) {
	return r.renameAreaImpl(ctx, input)
}

// RemoveArea is the resolver for the removeArea field.
func (r *mutationResolver) RemoveArea(ctx context.Context, input model.RemoveAreaInput) (*model.Config, error) {
	return r.removeAreaImpl(ctx, input)
}

// Type is the resolver for the type field. The stored Nib keeps Type empty when
// the file omits it, so the etag witnesses the on-disk bytes; this resolver
// applies the "task" presentation default. See nib.DefaultType.
func (r *nibResolver) Type(ctx context.Context, obj *nib.Nib) (string, error) {
	return obj.EffectiveType(), nil
}

// Priority is the resolver for the priority field. Mirrors Type: the stored Nib
// keeps Priority empty when the file omits it; this resolver applies "normal".
// See nib.DefaultPriority.
//
// Read-back limitation: updateNib(priority: null) stores "" on disk, but this
// resolver reports "normal" for empty, so a web round-trip that writes the read
// value back can self-revert the clear. Empty→normal is the data model; do not
// "fix" it here without also changing that model.
func (r *nibResolver) Priority(ctx context.Context, obj *nib.Nib) (string, error) {
	return obj.EffectivePriority(), nil
}

// ParentID is the resolver for the parentId field.
//
// Reports the RESOLVED parent id (see resolvedParent). Null both for a nib with
// no parent and for one whose stored link names no nib, so this field, the
// parent field, hasParent and siblingId all answer alike. The raw stored link is
// storedParentId.
func (r *nibResolver) ParentID(ctx context.Context, obj *nib.Nib) (*string, error) {
	id := resolvedParentID(obj, r.Reader)
	if id == "" {
		return nil, nil
	}
	return &id, nil
}

// StoredParentID is the resolver for the storedParentId field.
//
// The raw stored link, unresolved, so a broken one stays inspectable instead of
// reading as absent. Null only when the field is genuinely empty.
func (r *nibResolver) StoredParentID(ctx context.Context, obj *nib.Nib) (*string, error) {
	if obj.Parent == "" {
		return nil, nil
	}
	return &obj.Parent, nil
}

// BlockingIds is the resolver for the blockingIds field.
// Computed: nibs that have this nib in their blockedBy. A status that released
// its dependents (completed, scrapped) blocks nothing; a deferred nib is closed
// but still blocks.
func (r *nibResolver) BlockingIds(ctx context.Context, obj *nib.Nib) ([]string, error) {
	if r.releasesDependents(obj.Status) {
		return []string{}, nil
	}
	incoming := r.Reader.FindIncomingLinks(obj.ID)
	var ids []string
	for _, link := range incoming {
		if link.LinkType == "blocked_by" && !r.releasesDependents(link.FromNib.Status) {
			ids = append(ids, link.FromNib.ID)
		}
	}
	if ids == nil {
		ids = []string{}
	}
	return ids, nil
}

// BlockedByIds is the resolver for the blockedByIds field.
// Only blockers whose status has not released its dependents: completed and
// scrapped drop out, a deferred blocker stays.
func (r *nibResolver) BlockedByIds(ctx context.Context, obj *nib.Nib) ([]string, error) {
	var ids []string
	for _, blockerID := range obj.BlockedBy {
		if blocker, err := r.Reader.Get(blockerID); err == nil {
			if !r.releasesDependents(blocker.Status) {
				ids = append(ids, blockerID)
			}
		}
	}
	if ids == nil {
		ids = []string{}
	}
	return ids, nil
}

// BlockedBy is the resolver for the blockedBy field.
// Only blockers whose status has not released its dependents: completed and
// scrapped drop out, a deferred blocker stays.
func (r *nibResolver) BlockedBy(ctx context.Context, obj *nib.Nib, filter *model.NibFilter) ([]*nib.Nib, error) {
	var result []*nib.Nib
	for _, blockerID := range obj.BlockedBy {
		if blocker, ok := r.Reader.GetSnapshot(blockerID); ok {
			if !r.releasesDependents(blocker.Status) {
				result = append(result, blocker)
			}
		}
	}

	return ApplyFilter(ctx, result, filter, r.Reader, r.Resolver.Blocking)
}

// Blocking is the resolver for the blocking field.
// Computed: nibs whose BlockedBy contains this nib's ID. A status that released
// its dependents (completed, scrapped) blocks nothing; a deferred nib is closed
// but still blocks.
func (r *nibResolver) Blocking(ctx context.Context, obj *nib.Nib, filter *model.NibFilter) ([]*nib.Nib, error) {
	if r.releasesDependents(obj.Status) {
		return ApplyFilter(ctx, nil, filter, r.Reader, r.Resolver.Blocking)
	}
	incoming := r.Reader.FindIncomingLinks(obj.ID)
	var result []*nib.Nib
	for _, link := range incoming {
		if link.LinkType != "blocked_by" {
			continue
		}
		snap, ok := r.Reader.GetSnapshot(link.FromNib.ID)
		if ok && !r.releasesDependents(snap.Status) {
			result = append(result, snap)
		}
	}

	return ApplyFilter(ctx, result, filter, r.Reader, r.Resolver.Blocking)
}

// Parent is the resolver for the parent field.
// A broken parent link (absent target) resolves to nil.
func (r *nibResolver) Parent(ctx context.Context, obj *nib.Nib) (*nib.Nib, error) {
	if obj.Parent == "" {
		return nil, nil
	}
	snap, ok := r.Reader.GetSnapshot(obj.Parent)
	if !ok {
		return nil, nil
	}
	return snap, nil
}

// Children is the resolver for the children field.
func (r *nibResolver) Children(ctx context.Context, obj *nib.Nib, filter *model.NibFilter, sort *model.NibSort) ([]*nib.Nib, error) {
	siblings := r.Orderer.Members(ScopeParent, obj.ID)
	result := make([]*nib.Nib, 0, len(siblings))
	for _, sib := range siblings {
		if snap, ok := r.Reader.GetSnapshot(sib.ID); ok {
			result = append(result, snap)
		}
	}
	result, err := ApplyFilter(ctx, result, filter, r.Reader, r.Resolver.Blocking)
	if err != nil {
		return nil, err
	}
	ApplySorting(result, sort, r.Reader.Config())
	return result, nil
}

// MentionIds is the resolver for the mentionIds field.
// The IDs of nibs mentioned via `#<id>` in this nib's body. Mentions are
// informational and include every status, the closed ones included; for open
// nibs only, request `mentions` with a status filter — which matches literal
// names, with no open/closed group expansion at this layer.
func (r *nibResolver) MentionIds(ctx context.Context, obj *nib.Nib) ([]string, error) {
	return existingMentionIDs(r.Reader, cachedMentions(ctx, r.Reader, obj.ID)), nil
}

// MentionedByIds is the resolver for the mentionedByIds field.
// The IDs of nibs whose bodies mention this nib via `#<id>`. Mentions include
// every status, the closed ones included; for open nibs only, request
// `mentionedBy` with a status filter (see MentionIds).
func (r *nibResolver) MentionedByIds(ctx context.Context, obj *nib.Nib) ([]string, error) {
	return existingMentionIDs(r.Reader, cachedMentionedBy(ctx, r.Reader, obj.ID)), nil
}

// Mentions is the resolver for the mentions field.
// Mentions include every status, the closed ones included; for open nibs only,
// pass `filter: { status: [...] }` (see MentionIds). A mention that vanished
// before its snapshot is skipped.
func (r *nibResolver) Mentions(ctx context.Context, obj *nib.Nib, filter *model.NibFilter) ([]*nib.Nib, error) {
	mentioned := cachedMentions(ctx, r.Reader, obj.ID)
	result := make([]*nib.Nib, 0, len(mentioned))
	for _, m := range mentioned {
		if snap, ok := r.Reader.GetSnapshot(m.ID); ok {
			result = append(result, snap)
		}
	}
	return ApplyFilter(ctx, result, filter, r.Reader, r.Resolver.Blocking)
}

// MentionedBy is the resolver for the mentionedBy field.
// Mentions include every status, the closed ones included; for open nibs only,
// pass `filter: { status: [...] }` (see MentionIds). A source that vanished
// before its snapshot is skipped.
func (r *nibResolver) MentionedBy(ctx context.Context, obj *nib.Nib, filter *model.NibFilter) ([]*nib.Nib, error) {
	mentionedBy := cachedMentionedBy(ctx, r.Reader, obj.ID)
	result := make([]*nib.Nib, 0, len(mentionedBy))
	for _, m := range mentionedBy {
		if snap, ok := r.Reader.GetSnapshot(m.ID); ok {
			result = append(result, snap)
		}
	}
	return ApplyFilter(ctx, result, filter, r.Reader, r.Resolver.Blocking)
}

// Nib is the resolver for the nib field.
// A missing nib resolves to nil. GetSnapshot resolves short IDs as Get does.
func (r *queryResolver) Nib(ctx context.Context, id string) (*nib.Nib, error) {
	snap, ok := r.Reader.GetSnapshot(id)
	if !ok {
		return nil, nil
	}
	return snap, nil
}

// Nibs is the resolver for the nibs field.
//
// A search term SEEDS the input rather than being left to ApplyFilter's
// intersection branch: the seed carries the ORDER the schema promises for an
// unsorted search (id matches first, then full-text hits by relevance), which
// intersecting All() would lose. Seed from the reader, not cachedSearchAllIDs,
// whose memo keeps membership with the ranking discarded. A term alone seeds
// from Search, whose store-wide cap IS the answer; a term alongside a field
// that already bounds the set seeds from the uncapped SearchAll, where capping
// would drop a genuine member ranking below the global cutoff (see
// hasBoundingFilter).
func (r *queryResolver) Nibs(ctx context.Context, filter *model.NibFilter, sort *model.NibSort) ([]*nib.Nib, error) {
	var nibs []*nib.Nib

	searched := filter != nil && filter.Search != nil && *filter.Search != ""
	if searched {
		search := r.Reader.Search
		if hasBoundingFilter(filter) {
			search = r.Reader.SearchAll
		}
		searchResults, err := search(*filter.Search)
		if err != nil {
			return nil, err
		}
		nibs = searchResults

		// The seeded set already IS the term's answer, and nothing else in
		// ApplyFilter reads Search. Clear it on a LOCAL copy: writing back through
		// the caller's pointer would strip the term from a filter the caller still
		// holds and reuses, as cmd/list.go does for its hidden-closed count.
		unsearched := *filter
		unsearched.Search = nil
		filter = &unsearched
	} else {
		nibs = r.Reader.All()
	}

	result, err := ApplyFilter(ctx, nibs, filter, r.Reader, r.Blocking)
	if err != nil {
		return nil, err
	}

	// Ancestors of the matches, so a client can build complete trees from hits
	// that are all leaves.
	if searched {
		result = includeAncestors(result, r.Reader)
	}

	ApplySorting(result, sort, r.Reader.Config())

	// Detach: hand gqlgen snapshots, never the live pointers gathered above,
	// whose Path a concurrent Archive rewrites in place. This detaches the
	// RESULT only — the pipeline above reads non-Path fields off live pointers
	// and stays safe through the copy-on-write rule (see NibReader.GetSnapshot),
	// not through this step.
	snapshots := make([]*nib.Nib, 0, len(result))
	for _, b := range result {
		if snap, ok := r.Reader.GetSnapshot(b.ID); ok {
			snapshots = append(snapshots, snap)
		}
	}
	return snapshots, nil
}

// Config is the resolver for the config field.
func (r *queryResolver) Config(ctx context.Context) (*model.Config, error) {
	return configResult(r.Reader), nil
}

// UpdateStatus is the resolver for the updateStatus field. Best-effort: any
// gating (dev build / CI / opt-out) or network failure yields
// updateAvailable=false rather than failing the query.
func (r *queryResolver) UpdateStatus(ctx context.Context) (*model.UpdateStatus, error) {
	res, ok := updatecheck.NewChecker(r.Version).Check(ctx)
	return updateStatusResult(r.Version, res, ok), nil
}

// NibChanged is the resolver for the nibChanged field.
func (r *subscriptionResolver) NibChanged(ctx context.Context, id *string) (<-chan *model.NibChangeEvent, error) {
	eventCh, unsub := r.Subscriber.Subscribe()
	out := make(chan *model.NibChangeEvent)

	go func() {
		defer unsub()
		defer close(out)
		for {
			select {
			case <-ctx.Done():
				return
			case batch, ok := <-eventCh:
				if !ok {
					return
				}
				for _, evt := range batch {
					if id != nil && evt.NibID != *id {
						continue
					}
					// evt.Nib is already an immutable snapshot (see Core.Subscribe)
					// — safe to hand to gqlgen's async marshaler, path included,
					// without re-reading the store.
					event := &model.NibChangeEvent{
						Type:  evt.Type.String(),
						NibID: evt.NibID,
						Nib:   evt.Nib,
					}
					select {
					case out <- event:
					case <-ctx.Done():
						return
					}
				}
			}
		}
	}()

	return out, nil
}

// ConfigChanged is the resolver for the configChanged field.
//
// The tick carries no payload, so the config is READ at delivery time:
// NibReader.Areas is an atomic load of what the store declares now, and a client
// that missed a tick under backpressure receives the current vocabulary on the
// next one rather than a stale one held in a queue.
func (r *subscriptionResolver) ConfigChanged(ctx context.Context) (<-chan *model.Config, error) {
	ticks, unsub := r.Subscriber.SubscribeAreas()
	out := make(chan *model.Config)

	go func() {
		defer unsub()
		defer close(out)
		for {
			select {
			case <-ctx.Done():
				return
			case _, ok := <-ticks:
				if !ok {
					return
				}
				select {
				case out <- configResult(r.Reader):
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Nib returns NibResolver implementation.
func (r *Resolver) Nib() NibResolver { return &nibResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type (
	mutationResolver     struct{ *Resolver }
	nibResolver          struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
